// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="RewardRulesService.ListAsync"/>: List reward rules</summary>
    [SellAppModelSchema(false)]
    public class RewardRulesListOptions : ListOptions
    {
        /// <summary>Page number to return.</summary>
        [JsonProperty("page")]
        [STJS.JsonPropertyName("page")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? Page { get; set; }

        /// <summary>Set to false to return at most 100 matching items in one data array without pagination links or metadata.</summary>
        [JsonProperty("pagination")]
        [STJS.JsonPropertyName("pagination")]
        public bool? Pagination { get; set; }

    }

    /// <summary>Request options for <see cref="RewardRulesService.CreateAsync"/>: Create a reward rule</summary>
    [SellAppModelSchema(false)]
    public class RewardRulesCreateOptions : BaseOptions
    {
        [JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("name")]
        [SellAppSchemaConstraints(MinLength = 1, MaxLength = 120)]
        public string Name { get; set; } = default!;

        [JsonProperty("description")]
        [STJS.JsonPropertyName("description")]
        [SellAppSchemaConstraints(MaxLength = 255)]
        public string? Description { get; set; }

        [JsonProperty("is_active", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("is_active")]
        public bool IsActive { get; set; }

        [JsonProperty("trigger_type", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("trigger_type")]
        public SdkCreateRewardRuleRequestApplicationJsonTriggerType TriggerType { get; set; }

        [JsonProperty("trigger_threshold", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("trigger_threshold")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long TriggerThreshold { get; set; }

        [JsonProperty("outputs", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("outputs")]
        [SellAppSchemaConstraints(MinItems = 1)]
        public List<CreateRewardRuleRequestApplicationJsonPropertyOutputsItem> Outputs { get; set; } = default!;

        [JsonProperty("expected_updated_at")]
        [STJS.JsonPropertyName("expected_updated_at")]
        public DateTimeOffset? ExpectedUpdatedAt { get; set; }

    }

    /// <summary>Request options for <see cref="RewardRulesService.SearchAsync"/>: Search reward rules</summary>
    [SellAppModelSchema(false)]
    public class RewardRulesSearchOptions : ListOptions
    {
        [JsonProperty("filters")]
        [STJS.JsonPropertyName("filters")]
        public List<SearchRewardRulesRequestApplicationJsonPropertyFiltersItem>? Filters { get; set; }

        [JsonProperty("sort")]
        [STJS.JsonPropertyName("sort")]
        public List<SearchRewardRulesRequestApplicationJsonPropertySortItem>? Sort { get; set; }

        [JsonProperty("search")]
        [STJS.JsonPropertyName("search")]
        public SearchRewardRulesRequestApplicationJsonPropertySearch? Search { get; set; }

        [JsonProperty("includes")]
        [STJS.JsonPropertyName("includes")]
        public List<SearchRewardRulesRequestApplicationJsonPropertyIncludesItem>? Includes { get; set; }

        /// <summary>Page number to return.</summary>
        [JsonProperty("page")]
        [STJS.JsonPropertyName("page")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? Page { get; set; }

        /// <summary>Set to false to return at most 100 matching items in one data array without pagination links or metadata.</summary>
        [JsonProperty("pagination")]
        [STJS.JsonPropertyName("pagination")]
        public bool? Pagination { get; set; }

    }

    /// <summary>Request options for <see cref="RewardRulesService.ReplaceAsync"/>: Update a reward rule</summary>
    [SellAppModelSchema(false)]
    public class RewardRulesReplaceOptions : BaseOptions
    {
        [JsonProperty("name")]
        [STJS.JsonPropertyName("name")]
        [SellAppSchemaConstraints(MinLength = 1, MaxLength = 120)]
        public string? Name { get; set; }

        [JsonProperty("description")]
        [STJS.JsonPropertyName("description")]
        [SellAppSchemaConstraints(MaxLength = 255)]
        public string? Description { get; set; }

        [JsonProperty("is_active")]
        [STJS.JsonPropertyName("is_active")]
        public bool? IsActive { get; set; }

        [JsonProperty("trigger_type")]
        [STJS.JsonPropertyName("trigger_type")]
        public SdkReplaceRewardRuleRequestApplicationJsonTriggerType? TriggerType { get; set; }

        [JsonProperty("trigger_threshold")]
        [STJS.JsonPropertyName("trigger_threshold")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? TriggerThreshold { get; set; }

        [JsonProperty("outputs")]
        [STJS.JsonPropertyName("outputs")]
        [SellAppSchemaConstraints(MinItems = 1)]
        public List<ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItem>? Outputs { get; set; }

        [JsonProperty("expected_updated_at")]
        [STJS.JsonPropertyName("expected_updated_at")]
        public DateTimeOffset? ExpectedUpdatedAt { get; set; }

    }

    /// <summary>Request options for <see cref="RewardRulesService.UpdateAsync"/>: Update a reward rule</summary>
    [SellAppModelSchema(false)]
    public class RewardRulesUpdateOptions : BaseOptions
    {
        [JsonProperty("name")]
        [STJS.JsonPropertyName("name")]
        [SellAppSchemaConstraints(MinLength = 1, MaxLength = 120)]
        public string? Name { get; set; }

        [JsonProperty("description")]
        [STJS.JsonPropertyName("description")]
        [SellAppSchemaConstraints(MaxLength = 255)]
        public string? Description { get; set; }

        [JsonProperty("is_active")]
        [STJS.JsonPropertyName("is_active")]
        public bool? IsActive { get; set; }

        [JsonProperty("trigger_type")]
        [STJS.JsonPropertyName("trigger_type")]
        public SdkUpdateRewardRuleRequestApplicationJsonTriggerType? TriggerType { get; set; }

        [JsonProperty("trigger_threshold")]
        [STJS.JsonPropertyName("trigger_threshold")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? TriggerThreshold { get; set; }

        [JsonProperty("outputs")]
        [STJS.JsonPropertyName("outputs")]
        [SellAppSchemaConstraints(MinItems = 1)]
        public List<UpdateRewardRuleRequestApplicationJsonPropertyOutputsItem>? Outputs { get; set; }

        [JsonProperty("expected_updated_at")]
        [STJS.JsonPropertyName("expected_updated_at")]
        public DateTimeOffset? ExpectedUpdatedAt { get; set; }

    }
}
