// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents batch update product variants request application json property resources map value property deliverable property data property booking reminder offset unit values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit : ISellAppExtensibleEnum, IEquatable<BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit>
    {
        public BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit Unknown => new("unknown");
        public static BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit Minutes => new("minutes");
        public static BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit Hours => new("hours");
        public static BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit Days => new("days");
        public static BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit Weeks => new("weeks");

        public bool IsKnown => Value is "minutes" or "hours" or "days" or "weeks";
        public bool Equals(BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit(string value) => new(value);
        public static explicit operator string(BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit value) => value.Value;
        public static bool operator ==(BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit left, BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit right) => left.Equals(right);
        public static bool operator !=(BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit left, BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit right) => !left.Equals(right);
    }
}
