// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents create course lesson request application json property questions item question type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType : ISellAppExtensibleEnum, IEquatable<CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType>
    {
        public CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType Unknown => new("unknown");
        public static CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType Text => new("text");
        public static CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType SingleChoice => new("single_choice");
        public static CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType MultipleChoice => new("multiple_choice");

        public bool IsKnown => Value is "text" or "single_choice" or "multiple_choice";
        public bool Equals(CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType(string value) => new(value);
        public static explicit operator string(CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType value) => value.Value;
        public static bool operator ==(CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType left, CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType right) => left.Equals(right);
        public static bool operator !=(CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType left, CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType right) => !left.Equals(right);
    }
}
