// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents create reward rule response value201 application json property data trigger type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType : ISellAppExtensibleEnum, IEquatable<CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType>
    {
        public CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType Unknown => new("unknown");
        public static CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType PurchaseCount => new("PURCHASE_COUNT");
        public static CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType TotalSpent => new("TOTAL_SPENT");

        public bool IsKnown => Value is "PURCHASE_COUNT" or "TOTAL_SPENT";
        public bool Equals(CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType(string value) => new(value);
        public static explicit operator string(CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType value) => value.Value;
        public static bool operator ==(CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType left, CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType right) => left.Equals(right);
        public static bool operator !=(CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType left, CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType right) => !left.Equals(right);
    }
}
