// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents create add on draft request application json property variant property deliverable types values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes : ISellAppExtensibleEnum, IEquatable<CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes>
    {
        public CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes Unknown => new("unknown");
        public static CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes Downloadable => new("DOWNLOADABLE");
        public static CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes Text => new("TEXT");
        public static CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes Dynamic => new("DYNAMIC");
        public static CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes Manual => new("MANUAL");
        public static CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes LicenseKey => new("LICENSE_KEY");
        public static CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes Bundle => new("BUNDLE");
        public static CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes Booking => new("BOOKING");
        public static CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes Credits => new("CREDITS");

        public bool IsKnown => Value is "DOWNLOADABLE" or "TEXT" or "DYNAMIC" or "MANUAL" or "LICENSE_KEY" or "BUNDLE" or "BOOKING" or "CREDITS";
        public bool Equals(CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes(string value) => new(value);
        public static explicit operator string(CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes value) => value.Value;
        public static bool operator ==(CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes left, CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes right) => left.Equals(right);
        public static bool operator !=(CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes left, CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverableTypes right) => !left.Equals(right);
    }
}
