// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents create custom payment method response value201 application json property data type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType : ISellAppExtensibleEnum, IEquatable<CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType>
    {
        public CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType Unknown => new("unknown");
        public static CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType Instructions => new("instructions");
        public static CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType Redirect => new("redirect");

        public bool IsKnown => Value is "instructions" or "redirect";
        public bool Equals(CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType(string value) => new(value);
        public static explicit operator string(CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType value) => value.Value;
        public static bool operator ==(CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType left, CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType right) => left.Equals(right);
        public static bool operator !=(CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType left, CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType right) => !left.Equals(right);
    }
}
