// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents create reward rule response value201 application json property data property outputs item type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType : ISellAppExtensibleEnum, IEquatable<CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType>
    {
        public CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType Unknown => new("unknown");
        public static CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType WalletCredit => new("WALLET_CREDIT");
        public static CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType Coupon => new("COUPON");
        public static CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType Badge => new("BADGE");
        public static CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType StatusLabel => new("STATUS_LABEL");

        public bool IsKnown => Value is "WALLET_CREDIT" or "COUPON" or "BADGE" or "STATUS_LABEL";
        public bool Equals(CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType(string value) => new(value);
        public static explicit operator string(CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType value) => value.Value;
        public static bool operator ==(CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType left, CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType right) => left.Equals(right);
        public static bool operator !=(CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType left, CreateRewardRuleResponseValue201ApplicationJsonPropertyDataPropertyOutputsItemType right) => !left.Equals(right);
    }
}
