// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents create order refund response value200 application json property data property order status values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus : ISellAppExtensibleEnum, IEquatable<CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus>
    {
        public CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Unknown => new("unknown");
        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Pending => new("PENDING");
        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Reversed => new("REVERSED");
        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Partial => new("PARTIAL");
        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Voided => new("VOIDED");
        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Refunded => new("REFUNDED");
        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Paid => new("PAID");
        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Completed => new("COMPLETED");
        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Disputing => new("DISPUTING");
        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Review => new("REVIEW");
        public static CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus Failed => new("FAILED");

        public bool IsKnown => Value is "PENDING" or "REVERSED" or "PARTIAL" or "VOIDED" or "REFUNDED" or "PAID" or "COMPLETED" or "DISPUTING" or "REVIEW" or "FAILED";
        public bool Equals(CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus(string value) => new(value);
        public static explicit operator string(CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus value) => value.Value;
        public static bool operator ==(CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus left, CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus right) => left.Equals(right);
        public static bool operator !=(CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus left, CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderStatus right) => !left.Equals(right);
    }
}
