// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents create export request application json property parameters report type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct CreateExportRequestApplicationJsonPropertyParametersReportType : ISellAppExtensibleEnum, IEquatable<CreateExportRequestApplicationJsonPropertyParametersReportType>
    {
        public CreateExportRequestApplicationJsonPropertyParametersReportType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static CreateExportRequestApplicationJsonPropertyParametersReportType Unknown => new("unknown");
        public static CreateExportRequestApplicationJsonPropertyParametersReportType Summary => new("summary");
        public static CreateExportRequestApplicationJsonPropertyParametersReportType Detailed => new("detailed");

        public bool IsKnown => Value is "summary" or "detailed";
        public bool Equals(CreateExportRequestApplicationJsonPropertyParametersReportType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is CreateExportRequestApplicationJsonPropertyParametersReportType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator CreateExportRequestApplicationJsonPropertyParametersReportType(string value) => new(value);
        public static explicit operator string(CreateExportRequestApplicationJsonPropertyParametersReportType value) => value.Value;
        public static bool operator ==(CreateExportRequestApplicationJsonPropertyParametersReportType left, CreateExportRequestApplicationJsonPropertyParametersReportType right) => left.Equals(right);
        public static bool operator !=(CreateExportRequestApplicationJsonPropertyParametersReportType left, CreateExportRequestApplicationJsonPropertyParametersReportType right) => !left.Equals(right);
    }
}
