// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents create reward coupon template response value201 application json property data type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType : ISellAppExtensibleEnum, IEquatable<CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType>
    {
        public CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType Unknown => new("unknown");
        public static CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType Percentage => new("PERCENTAGE");
        public static CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType Amount => new("AMOUNT");

        public bool IsKnown => Value is "PERCENTAGE" or "AMOUNT";
        public bool Equals(CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType(string value) => new(value);
        public static explicit operator string(CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType value) => value.Value;
        public static bool operator ==(CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType left, CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType right) => left.Equals(right);
        public static bool operator !=(CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType left, CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyDataType right) => !left.Equals(right);
    }
}
