// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents delete highlight response value200 application json property data property media item type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType : ISellAppExtensibleEnum, IEquatable<DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType>
    {
        public DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType Unknown => new("unknown");
        public static DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType Image => new("image");
        public static DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType Video => new("video");

        public bool IsKnown => Value is "image" or "video";
        public bool Equals(DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType(string value) => new(value);
        public static explicit operator string(DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType value) => value.Value;
        public static bool operator ==(DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType left, DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType right) => left.Equals(right);
        public static bool operator !=(DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType left, DeleteHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItemType right) => !left.Equals(right);
    }
}
