// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents get custom payment method response value200 application json property data type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType : ISellAppExtensibleEnum, IEquatable<GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType>
    {
        public GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType Unknown => new("unknown");
        public static GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType Instructions => new("instructions");
        public static GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType Redirect => new("redirect");

        public bool IsKnown => Value is "instructions" or "redirect";
        public bool Equals(GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType(string value) => new(value);
        public static explicit operator string(GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType value) => value.Value;
        public static bool operator ==(GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType left, GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType right) => left.Equals(right);
        public static bool operator !=(GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType left, GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataType right) => !left.Equals(right);
    }
}
