// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents get export response value200 application json property data type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct GetExportResponseValue200ApplicationJsonPropertyDataType : ISellAppExtensibleEnum, IEquatable<GetExportResponseValue200ApplicationJsonPropertyDataType>
    {
        public GetExportResponseValue200ApplicationJsonPropertyDataType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static GetExportResponseValue200ApplicationJsonPropertyDataType Unknown => new("unknown");
        public static GetExportResponseValue200ApplicationJsonPropertyDataType Sales => new("sales");
        public static GetExportResponseValue200ApplicationJsonPropertyDataType Tax => new("tax");
        public static GetExportResponseValue200ApplicationJsonPropertyDataType Customers => new("customers");
        public static GetExportResponseValue200ApplicationJsonPropertyDataType AffiliatePayouts => new("affiliate_payouts");

        public bool IsKnown => Value is "sales" or "tax" or "customers" or "affiliate_payouts";
        public bool Equals(GetExportResponseValue200ApplicationJsonPropertyDataType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is GetExportResponseValue200ApplicationJsonPropertyDataType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator GetExportResponseValue200ApplicationJsonPropertyDataType(string value) => new(value);
        public static explicit operator string(GetExportResponseValue200ApplicationJsonPropertyDataType value) => value.Value;
        public static bool operator ==(GetExportResponseValue200ApplicationJsonPropertyDataType left, GetExportResponseValue200ApplicationJsonPropertyDataType right) => left.Equals(right);
        public static bool operator !=(GetExportResponseValue200ApplicationJsonPropertyDataType left, GetExportResponseValue200ApplicationJsonPropertyDataType right) => !left.Equals(right);
    }
}
