// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents get invoice deliverables response value200 application json property data item property deliverable types values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes : ISellAppExtensibleEnum, IEquatable<GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes>
    {
        public GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes Unknown => new("unknown");
        public static GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes Downloadable => new("DOWNLOADABLE");
        public static GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes Text => new("TEXT");
        public static GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes Dynamic => new("DYNAMIC");
        public static GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes Manual => new("MANUAL");
        public static GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes LicenseKey => new("LICENSE_KEY");
        public static GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes Bundle => new("BUNDLE");
        public static GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes Booking => new("BOOKING");
        public static GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes Credits => new("CREDITS");

        public bool IsKnown => Value is "DOWNLOADABLE" or "TEXT" or "DYNAMIC" or "MANUAL" or "LICENSE_KEY" or "BUNDLE" or "BOOKING" or "CREDITS";
        public bool Equals(GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes(string value) => new(value);
        public static explicit operator string(GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes value) => value.Value;
        public static bool operator ==(GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes left, GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes right) => left.Equals(right);
        public static bool operator !=(GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes left, GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverableTypes right) => !left.Equals(right);
    }
}
