// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents get notification channel response value200 application json property data type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType : ISellAppExtensibleEnum, IEquatable<GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType>
    {
        public GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType Unknown => new("unknown");
        public static GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType Email => new("email");
        public static GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType Discord => new("discord");

        public bool IsKnown => Value is "email" or "discord";
        public bool Equals(GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType(string value) => new(value);
        public static explicit operator string(GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType value) => value.Value;
        public static bool operator ==(GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType left, GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType right) => left.Equals(right);
        public static bool operator !=(GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType left, GetNotificationChannelResponseValue200ApplicationJsonPropertyDataType right) => !left.Equals(right);
    }
}
