// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents get order s line item response value200 application json property data property fulfillment types values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes : ISellAppExtensibleEnum, IEquatable<GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes>
    {
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes Unknown => new("unknown");
        public static GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes Downloadable => new("DOWNLOADABLE");
        public static GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes Text => new("TEXT");
        public static GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes Dynamic => new("DYNAMIC");
        public static GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes Manual => new("MANUAL");
        public static GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes LicenseKey => new("LICENSE_KEY");
        public static GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes Bundle => new("BUNDLE");
        public static GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes Booking => new("BOOKING");
        public static GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes Credits => new("CREDITS");

        public bool IsKnown => Value is "DOWNLOADABLE" or "TEXT" or "DYNAMIC" or "MANUAL" or "LICENSE_KEY" or "BUNDLE" or "BOOKING" or "CREDITS";
        public bool Equals(GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes(string value) => new(value);
        public static explicit operator string(GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes value) => value.Value;
        public static bool operator ==(GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes left, GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes right) => left.Equals(right);
        public static bool operator !=(GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes left, GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillmentTypes right) => !left.Equals(right);
    }
}
