// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents get payment method status response value200 application json property data property required input item type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType : ISellAppExtensibleEnum, IEquatable<GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType>
    {
        public GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType Unknown => new("unknown");
        public static GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType String => new("string");
        public static GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType Enum => new("enum");
        public static GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType Boolean => new("boolean");
        public static GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType Array => new("array");
        public static GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType Decimal => new("decimal");

        public bool IsKnown => Value is "string" or "enum" or "boolean" or "array" or "decimal";
        public bool Equals(GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType(string value) => new(value);
        public static explicit operator string(GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType value) => value.Value;
        public static bool operator ==(GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType left, GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType right) => left.Equals(right);
        public static bool operator !=(GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType left, GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType right) => !left.Equals(right);
    }
}
