// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents get refund response value200 application json property data property refundable type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType : ISellAppExtensibleEnum, IEquatable<GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType>
    {
        public GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType Unknown => new("unknown");
        public static GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType Order => new("order");
        public static GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType Charge => new("charge");

        public bool IsKnown => Value is "order" or "charge";
        public bool Equals(GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType(string value) => new(value);
        public static explicit operator string(GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType value) => value.Value;
        public static bool operator ==(GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType left, GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType right) => left.Equals(right);
        public static bool operator !=(GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType left, GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundableType right) => !left.Equals(right);
    }
}
