// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents license length unit values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct LicenseLengthUnit : ISellAppExtensibleEnum, IEquatable<LicenseLengthUnit>
    {
        public LicenseLengthUnit(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static LicenseLengthUnit Unknown => new("unknown");
        public static LicenseLengthUnit Day => new("DAY");
        public static LicenseLengthUnit Month => new("MONTH");
        public static LicenseLengthUnit Year => new("YEAR");
        public static LicenseLengthUnit Null => new("null");

        public bool IsKnown => Value is "DAY" or "MONTH" or "YEAR" or "null";
        public bool Equals(LicenseLengthUnit other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is LicenseLengthUnit other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator LicenseLengthUnit(string value) => new(value);
        public static explicit operator string(LicenseLengthUnit value) => value.Value;
        public static bool operator ==(LicenseLengthUnit left, LicenseLengthUnit right) => left.Equals(right);
        public static bool operator !=(LicenseLengthUnit left, LicenseLengthUnit right) => !left.Equals(right);
    }
}
