// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents reorder course sections response value200 application json property data property sections item property lessons item type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType : ISellAppExtensibleEnum, IEquatable<ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType>
    {
        public ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType Unknown => new("unknown");
        public static ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType Lecture => new("lecture");
        public static ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType Video => new("video");
        public static ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType Text => new("text");
        public static ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType Quiz => new("quiz");
        public static ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType Assignment => new("assignment");

        public bool IsKnown => Value is "lecture" or "video" or "text" or "quiz" or "assignment";
        public bool Equals(ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType(string value) => new(value);
        public static explicit operator string(ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType value) => value.Value;
        public static bool operator ==(ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType left, ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType right) => left.Equals(right);
        public static bool operator !=(ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType left, ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemType right) => !left.Equals(right);
    }
}
