// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents replace course section response value200 application json property data property lessons item type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType : ISellAppExtensibleEnum, IEquatable<ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType>
    {
        public ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType Unknown => new("unknown");
        public static ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType Lecture => new("lecture");
        public static ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType Video => new("video");
        public static ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType Text => new("text");
        public static ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType Quiz => new("quiz");
        public static ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType Assignment => new("assignment");

        public bool IsKnown => Value is "lecture" or "video" or "text" or "quiz" or "assignment";
        public bool Equals(ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType(string value) => new(value);
        public static explicit operator string(ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType value) => value.Value;
        public static bool operator ==(ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType left, ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType right) => left.Equals(right);
        public static bool operator !=(ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType left, ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType right) => !left.Equals(right);
    }
}
