// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents replace promotion response value200 application json property data status values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus : ISellAppExtensibleEnum, IEquatable<ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus>
    {
        public ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus Unknown => new("unknown");
        public static ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus Active => new("active");
        public static ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus Disabled => new("disabled");

        public bool IsKnown => Value is "active" or "disabled";
        public bool Equals(ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus(string value) => new(value);
        public static explicit operator string(ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus value) => value.Value;
        public static bool operator ==(ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus left, ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus right) => left.Equals(right);
        public static bool operator !=(ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus left, ReplacePromotionResponseValue200ApplicationJsonPropertyDataStatus right) => !left.Equals(right);
    }
}
