// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents replace product variant with put request application json property deliverable types values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes : ISellAppExtensibleEnum, IEquatable<ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes>
    {
        public ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes Unknown => new("unknown");
        public static ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes Downloadable => new("DOWNLOADABLE");
        public static ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes Text => new("TEXT");
        public static ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes Dynamic => new("DYNAMIC");
        public static ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes Manual => new("MANUAL");
        public static ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes LicenseKey => new("LICENSE_KEY");
        public static ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes Bundle => new("BUNDLE");
        public static ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes Booking => new("BOOKING");
        public static ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes Credits => new("CREDITS");

        public bool IsKnown => Value is "DOWNLOADABLE" or "TEXT" or "DYNAMIC" or "MANUAL" or "LICENSE_KEY" or "BUNDLE" or "BOOKING" or "CREDITS";
        public bool Equals(ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes(string value) => new(value);
        public static explicit operator string(ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes value) => value.Value;
        public static bool operator ==(ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes left, ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes right) => left.Equals(right);
        public static bool operator !=(ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes left, ReplaceProductVariantWithPutRequestApplicationJsonPropertyDeliverableTypes right) => !left.Equals(right);
    }
}
