// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents replace course lesson response value200 application json property data property assignment value property questions item question type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType : ISellAppExtensibleEnum, IEquatable<ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType>
    {
        public ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType Unknown => new("unknown");
        public static ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType Text => new("text");
        public static ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType SingleChoice => new("single_choice");
        public static ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType MultipleChoice => new("multiple_choice");

        public bool IsKnown => Value is "text" or "single_choice" or "multiple_choice";
        public bool Equals(ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType(string value) => new(value);
        public static explicit operator string(ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType value) => value.Value;
        public static bool operator ==(ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType left, ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType right) => left.Equals(right);
        public static bool operator !=(ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType left, ReplaceCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyAssignmentValuePropertyQuestionsItemQuestionType right) => !left.Equals(right);
    }
}
