// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents replace booking configuration response value200 application json property data reminder offset unit values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit : ISellAppExtensibleEnum, IEquatable<ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit>
    {
        public ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit Unknown => new("unknown");
        public static ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit Minutes => new("minutes");
        public static ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit Hours => new("hours");
        public static ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit Days => new("days");
        public static ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit Weeks => new("weeks");

        public bool IsKnown => Value is "minutes" or "hours" or "days" or "weeks";
        public bool Equals(ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit(string value) => new(value);
        public static explicit operator string(ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit value) => value.Value;
        public static bool operator ==(ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit left, ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit right) => left.Equals(right);
        public static bool operator !=(ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit left, ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataReminderOffsetUnit right) => !left.Equals(right);
    }
}
