// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents replace reward rule request application json property outputs item type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType : ISellAppExtensibleEnum, IEquatable<ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType>
    {
        public ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType Unknown => new("unknown");
        public static ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType WalletCredit => new("WALLET_CREDIT");
        public static ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType Coupon => new("COUPON");
        public static ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType Badge => new("BADGE");
        public static ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType StatusLabel => new("STATUS_LABEL");

        public bool IsKnown => Value is "WALLET_CREDIT" or "COUPON" or "BADGE" or "STATUS_LABEL";
        public bool Equals(ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType(string value) => new(value);
        public static explicit operator string(ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType value) => value.Value;
        public static bool operator ==(ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType left, ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType right) => left.Equals(right);
        public static bool operator !=(ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType left, ReplaceRewardRuleRequestApplicationJsonPropertyOutputsItemType right) => !left.Equals(right);
    }
}
