// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents sdk create product variant request application json payment methods values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct SdkCreateProductVariantRequestApplicationJsonPaymentMethods : ISellAppExtensibleEnum, IEquatable<SdkCreateProductVariantRequestApplicationJsonPaymentMethods>
    {
        public SdkCreateProductVariantRequestApplicationJsonPaymentMethods(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Unknown => new("unknown");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Authnet => new("AUTHNET");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Btcpay => new("BTCPAY");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Cashapp => new("CASHAPP");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Coinbase => new("COINBASE");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Paddle => new("PADDLE");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Paydash => new("PAYDASH");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Paypal => new("PAYPAL");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Paystack => new("PAYSTACK");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Square => new("SQUARE");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Stripe => new("STRIPE");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Venmo => new("VENMO");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Nmi => new("NMI");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods MercadoPago => new("MERCADO_PAGO");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Mollie => new("MOLLIE");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Razorpay => new("RAZORPAY");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods CustomPaymentMethod => new("CUSTOM_PAYMENT_METHOD");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Lifi => new("LIFI");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Btc => new("BTC");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Ltc => new("LTC");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Eth => new("ETH");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Xmr => new("XMR");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Sol => new("SOL");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Ada => new("ADA");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Bnb => new("BNB");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Trx => new("TRX");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods Matic => new("MATIC");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods EthUsdt => new("ETH_USDT");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods EthUsdc => new("ETH_USDC");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods EthUni => new("ETH_UNI");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods EthShib => new("ETH_SHIB");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods EthDai => new("ETH_DAI");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods BnbUsdt => new("BNB_USDT");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods BnbUsdc => new("BNB_USDC");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods TrxUsdt => new("TRX_USDT");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods TrxUsdc => new("TRX_USDC");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods SolUsdt => new("SOL_USDT");
        public static SdkCreateProductVariantRequestApplicationJsonPaymentMethods SolUsdc => new("SOL_USDC");

        public bool IsKnown => Value is "AUTHNET" or "BTCPAY" or "CASHAPP" or "COINBASE" or "PADDLE" or "PAYDASH" or "PAYPAL" or "PAYSTACK" or "SQUARE" or "STRIPE" or "VENMO" or "NMI" or "MERCADO_PAGO" or "MOLLIE" or "RAZORPAY" or "CUSTOM_PAYMENT_METHOD" or "LIFI" or "BTC" or "LTC" or "ETH" or "XMR" or "SOL" or "ADA" or "BNB" or "TRX" or "MATIC" or "ETH_USDT" or "ETH_USDC" or "ETH_UNI" or "ETH_SHIB" or "ETH_DAI" or "BNB_USDT" or "BNB_USDC" or "TRX_USDT" or "TRX_USDC" or "SOL_USDT" or "SOL_USDC";
        public bool Equals(SdkCreateProductVariantRequestApplicationJsonPaymentMethods other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is SdkCreateProductVariantRequestApplicationJsonPaymentMethods other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator SdkCreateProductVariantRequestApplicationJsonPaymentMethods(string value) => new(value);
        public static explicit operator string(SdkCreateProductVariantRequestApplicationJsonPaymentMethods value) => value.Value;
        public static bool operator ==(SdkCreateProductVariantRequestApplicationJsonPaymentMethods left, SdkCreateProductVariantRequestApplicationJsonPaymentMethods right) => left.Equals(right);
        public static bool operator !=(SdkCreateProductVariantRequestApplicationJsonPaymentMethods left, SdkCreateProductVariantRequestApplicationJsonPaymentMethods right) => !left.Equals(right);
    }
}
