// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents sdk confirm subscription plan change request application json proration behavior values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior : ISellAppExtensibleEnum, IEquatable<SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior>
    {
        public SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior Unknown => new("unknown");
        public static SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior InvoiceNow => new("invoice_now");
        public static SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior CreditNextInvoice => new("credit_next_invoice");
        public static SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior None => new("none");
        public static SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior ProviderDefault => new("provider_default");

        public bool IsKnown => Value is "invoice_now" or "credit_next_invoice" or "none" or "provider_default";
        public bool Equals(SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior(string value) => new(value);
        public static explicit operator string(SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior value) => value.Value;
        public static bool operator ==(SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior left, SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior right) => left.Equals(right);
        public static bool operator !=(SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior left, SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior right) => !left.Equals(right);
    }
}
