// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents sdk create order request application json payment method values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct SdkCreateOrderRequestApplicationJsonPaymentMethod : ISellAppExtensibleEnum, IEquatable<SdkCreateOrderRequestApplicationJsonPaymentMethod>
    {
        public SdkCreateOrderRequestApplicationJsonPaymentMethod(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Unknown => new("unknown");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Authnet => new("AUTHNET");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Btcpay => new("BTCPAY");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Cashapp => new("CASHAPP");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Coinbase => new("COINBASE");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Paddle => new("PADDLE");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Paydash => new("PAYDASH");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Paypal => new("PAYPAL");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Paystack => new("PAYSTACK");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Square => new("SQUARE");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Stripe => new("STRIPE");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Venmo => new("VENMO");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Nmi => new("NMI");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod MercadoPago => new("MERCADO_PAGO");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Mollie => new("MOLLIE");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Razorpay => new("RAZORPAY");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod CustomPaymentMethod => new("CUSTOM_PAYMENT_METHOD");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Lifi => new("LIFI");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Btc => new("BTC");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Ltc => new("LTC");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Eth => new("ETH");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Xmr => new("XMR");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Sol => new("SOL");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Ada => new("ADA");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Bnb => new("BNB");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Trx => new("TRX");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod Matic => new("MATIC");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod EthUsdt => new("ETH_USDT");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod EthUsdc => new("ETH_USDC");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod EthUni => new("ETH_UNI");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod EthShib => new("ETH_SHIB");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod EthDai => new("ETH_DAI");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod BnbUsdt => new("BNB_USDT");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod BnbUsdc => new("BNB_USDC");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod TrxUsdt => new("TRX_USDT");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod TrxUsdc => new("TRX_USDC");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod SolUsdt => new("SOL_USDT");
        public static SdkCreateOrderRequestApplicationJsonPaymentMethod SolUsdc => new("SOL_USDC");

        public bool IsKnown => Value is "AUTHNET" or "BTCPAY" or "CASHAPP" or "COINBASE" or "PADDLE" or "PAYDASH" or "PAYPAL" or "PAYSTACK" or "SQUARE" or "STRIPE" or "VENMO" or "NMI" or "MERCADO_PAGO" or "MOLLIE" or "RAZORPAY" or "CUSTOM_PAYMENT_METHOD" or "LIFI" or "BTC" or "LTC" or "ETH" or "XMR" or "SOL" or "ADA" or "BNB" or "TRX" or "MATIC" or "ETH_USDT" or "ETH_USDC" or "ETH_UNI" or "ETH_SHIB" or "ETH_DAI" or "BNB_USDT" or "BNB_USDC" or "TRX_USDT" or "TRX_USDC" or "SOL_USDT" or "SOL_USDC";
        public bool Equals(SdkCreateOrderRequestApplicationJsonPaymentMethod other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is SdkCreateOrderRequestApplicationJsonPaymentMethod other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator SdkCreateOrderRequestApplicationJsonPaymentMethod(string value) => new(value);
        public static explicit operator string(SdkCreateOrderRequestApplicationJsonPaymentMethod value) => value.Value;
        public static bool operator ==(SdkCreateOrderRequestApplicationJsonPaymentMethod left, SdkCreateOrderRequestApplicationJsonPaymentMethod right) => left.Equals(right);
        public static bool operator !=(SdkCreateOrderRequestApplicationJsonPaymentMethod left, SdkCreateOrderRequestApplicationJsonPaymentMethod right) => !left.Equals(right);
    }
}
