// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents sdk replace reward rule request application json trigger type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct SdkReplaceRewardRuleRequestApplicationJsonTriggerType : ISellAppExtensibleEnum, IEquatable<SdkReplaceRewardRuleRequestApplicationJsonTriggerType>
    {
        public SdkReplaceRewardRuleRequestApplicationJsonTriggerType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static SdkReplaceRewardRuleRequestApplicationJsonTriggerType Unknown => new("unknown");
        public static SdkReplaceRewardRuleRequestApplicationJsonTriggerType PurchaseCount => new("PURCHASE_COUNT");
        public static SdkReplaceRewardRuleRequestApplicationJsonTriggerType TotalSpent => new("TOTAL_SPENT");

        public bool IsKnown => Value is "PURCHASE_COUNT" or "TOTAL_SPENT";
        public bool Equals(SdkReplaceRewardRuleRequestApplicationJsonTriggerType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is SdkReplaceRewardRuleRequestApplicationJsonTriggerType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator SdkReplaceRewardRuleRequestApplicationJsonTriggerType(string value) => new(value);
        public static explicit operator string(SdkReplaceRewardRuleRequestApplicationJsonTriggerType value) => value.Value;
        public static bool operator ==(SdkReplaceRewardRuleRequestApplicationJsonTriggerType left, SdkReplaceRewardRuleRequestApplicationJsonTriggerType right) => left.Equals(right);
        public static bool operator !=(SdkReplaceRewardRuleRequestApplicationJsonTriggerType left, SdkReplaceRewardRuleRequestApplicationJsonTriggerType right) => !left.Equals(right);
    }
}
