// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents sdk replace product variant pricing request application json payment methods values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods : ISellAppExtensibleEnum, IEquatable<SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods>
    {
        public SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Unknown => new("unknown");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Authnet => new("AUTHNET");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Btcpay => new("BTCPAY");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Cashapp => new("CASHAPP");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Coinbase => new("COINBASE");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Paddle => new("PADDLE");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Paydash => new("PAYDASH");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Paypal => new("PAYPAL");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Paystack => new("PAYSTACK");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Square => new("SQUARE");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Stripe => new("STRIPE");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Venmo => new("VENMO");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Nmi => new("NMI");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods MercadoPago => new("MERCADO_PAGO");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Mollie => new("MOLLIE");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Razorpay => new("RAZORPAY");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods CustomPaymentMethod => new("CUSTOM_PAYMENT_METHOD");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Lifi => new("LIFI");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Btc => new("BTC");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Ltc => new("LTC");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Eth => new("ETH");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Xmr => new("XMR");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Sol => new("SOL");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Ada => new("ADA");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Bnb => new("BNB");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Trx => new("TRX");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods Matic => new("MATIC");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods EthUsdt => new("ETH_USDT");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods EthUsdc => new("ETH_USDC");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods EthUni => new("ETH_UNI");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods EthShib => new("ETH_SHIB");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods EthDai => new("ETH_DAI");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods BnbUsdt => new("BNB_USDT");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods BnbUsdc => new("BNB_USDC");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods TrxUsdt => new("TRX_USDT");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods TrxUsdc => new("TRX_USDC");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods SolUsdt => new("SOL_USDT");
        public static SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods SolUsdc => new("SOL_USDC");

        public bool IsKnown => Value is "AUTHNET" or "BTCPAY" or "CASHAPP" or "COINBASE" or "PADDLE" or "PAYDASH" or "PAYPAL" or "PAYSTACK" or "SQUARE" or "STRIPE" or "VENMO" or "NMI" or "MERCADO_PAGO" or "MOLLIE" or "RAZORPAY" or "CUSTOM_PAYMENT_METHOD" or "LIFI" or "BTC" or "LTC" or "ETH" or "XMR" or "SOL" or "ADA" or "BNB" or "TRX" or "MATIC" or "ETH_USDT" or "ETH_USDC" or "ETH_UNI" or "ETH_SHIB" or "ETH_DAI" or "BNB_USDT" or "BNB_USDC" or "TRX_USDT" or "TRX_USDC" or "SOL_USDT" or "SOL_USDC";
        public bool Equals(SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods(string value) => new(value);
        public static explicit operator string(SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods value) => value.Value;
        public static bool operator ==(SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods left, SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods right) => left.Equals(right);
        public static bool operator !=(SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods left, SdkReplaceProductVariantPricingRequestApplicationJsonPaymentMethods right) => !left.Equals(right);
    }
}
