// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents sdk record credit transaction request application json kind values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct SdkRecordCreditTransactionRequestApplicationJsonKind : ISellAppExtensibleEnum, IEquatable<SdkRecordCreditTransactionRequestApplicationJsonKind>
    {
        public SdkRecordCreditTransactionRequestApplicationJsonKind(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static SdkRecordCreditTransactionRequestApplicationJsonKind Unknown => new("unknown");
        public static SdkRecordCreditTransactionRequestApplicationJsonKind Grant => new("grant");
        public static SdkRecordCreditTransactionRequestApplicationJsonKind Consumption => new("consumption");
        public static SdkRecordCreditTransactionRequestApplicationJsonKind Adjustment => new("adjustment");

        public bool IsKnown => Value is "grant" or "consumption" or "adjustment";
        public bool Equals(SdkRecordCreditTransactionRequestApplicationJsonKind other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is SdkRecordCreditTransactionRequestApplicationJsonKind other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator SdkRecordCreditTransactionRequestApplicationJsonKind(string value) => new(value);
        public static explicit operator string(SdkRecordCreditTransactionRequestApplicationJsonKind value) => value.Value;
        public static bool operator ==(SdkRecordCreditTransactionRequestApplicationJsonKind left, SdkRecordCreditTransactionRequestApplicationJsonKind right) => left.Equals(right);
        public static bool operator !=(SdkRecordCreditTransactionRequestApplicationJsonKind left, SdkRecordCreditTransactionRequestApplicationJsonKind right) => !left.Equals(right);
    }
}
