// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents sdk replace webhook channel request application json allowed notifications values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications : ISellAppExtensibleEnum, IEquatable<SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications>
    {
        public SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications Unknown => new("unknown");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications BookingCancelled => new("booking.cancelled");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications BookingRescheduled => new("booking.rescheduled");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications CashAppPaymentRequiresAttention => new("cash_app.payment_requires_attention");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications ChargeCompleted => new("charge.completed");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications ChargeCreated => new("charge.created");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications ChargeDisputed => new("charge.disputed");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications ChargePartialPaid => new("charge.partial_paid");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications ChargeReview => new("charge.review");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications FeedbackCreated => new("feedback.created");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications OrderCompleted => new("order.completed");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications OrderCreated => new("order.created");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications OrderDisputed => new("order.disputed");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications OrderManualPaymentCompleted => new("order.manual_payment_completed");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications OrderPaid => new("order.paid");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications OrderPartialPaid => new("order.partial_paid");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications ProductCreated => new("product.created");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications ProductTrashed => new("product.trashed");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications ProductUpdated => new("product.updated");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications SubscriptionCancelled => new("subscription.cancelled");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications SubscriptionCreated => new("subscription.created");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications SubscriptionRenewed => new("subscription.renewed");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications TicketMessageCreated => new("ticket_message.created");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications VariantCreated => new("variant.created");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications VariantSoldOut => new("variant.sold_out");
        public static SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications VariantUpdated => new("variant.updated");

        public bool IsKnown => Value is "booking.cancelled" or "booking.rescheduled" or "cash_app.payment_requires_attention" or "charge.completed" or "charge.created" or "charge.disputed" or "charge.partial_paid" or "charge.review" or "feedback.created" or "order.completed" or "order.created" or "order.disputed" or "order.manual_payment_completed" or "order.paid" or "order.partial_paid" or "product.created" or "product.trashed" or "product.updated" or "subscription.cancelled" or "subscription.created" or "subscription.renewed" or "ticket_message.created" or "variant.created" or "variant.sold_out" or "variant.updated";
        public bool Equals(SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications(string value) => new(value);
        public static explicit operator string(SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications value) => value.Value;
        public static bool operator ==(SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications left, SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications right) => left.Equals(right);
        public static bool operator !=(SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications left, SdkReplaceWebhookChannelRequestApplicationJsonAllowedNotifications right) => !left.Equals(right);
    }
}
