// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents search customers request application json property sort item direction values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct SearchCustomersRequestApplicationJsonPropertySortItemDirection : ISellAppExtensibleEnum, IEquatable<SearchCustomersRequestApplicationJsonPropertySortItemDirection>
    {
        public SearchCustomersRequestApplicationJsonPropertySortItemDirection(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static SearchCustomersRequestApplicationJsonPropertySortItemDirection Unknown => new("unknown");
        public static SearchCustomersRequestApplicationJsonPropertySortItemDirection Asc => new("asc");
        public static SearchCustomersRequestApplicationJsonPropertySortItemDirection Desc => new("desc");

        public bool IsKnown => Value is "asc" or "desc";
        public bool Equals(SearchCustomersRequestApplicationJsonPropertySortItemDirection other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is SearchCustomersRequestApplicationJsonPropertySortItemDirection other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator SearchCustomersRequestApplicationJsonPropertySortItemDirection(string value) => new(value);
        public static explicit operator string(SearchCustomersRequestApplicationJsonPropertySortItemDirection value) => value.Value;
        public static bool operator ==(SearchCustomersRequestApplicationJsonPropertySortItemDirection left, SearchCustomersRequestApplicationJsonPropertySortItemDirection right) => left.Equals(right);
        public static bool operator !=(SearchCustomersRequestApplicationJsonPropertySortItemDirection left, SearchCustomersRequestApplicationJsonPropertySortItemDirection right) => !left.Equals(right);
    }
}
