// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents search customers request application json property sort item field values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct SearchCustomersRequestApplicationJsonPropertySortItemField : ISellAppExtensibleEnum, IEquatable<SearchCustomersRequestApplicationJsonPropertySortItemField>
    {
        public SearchCustomersRequestApplicationJsonPropertySortItemField(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static SearchCustomersRequestApplicationJsonPropertySortItemField Unknown => new("unknown");
        public static SearchCustomersRequestApplicationJsonPropertySortItemField Id => new("id");
        public static SearchCustomersRequestApplicationJsonPropertySortItemField Email => new("email");
        public static SearchCustomersRequestApplicationJsonPropertySortItemField CreatedAt => new("created_at");
        public static SearchCustomersRequestApplicationJsonPropertySortItemField UpdatedAt => new("updated_at");

        public bool IsKnown => Value is "id" or "email" or "created_at" or "updated_at";
        public bool Equals(SearchCustomersRequestApplicationJsonPropertySortItemField other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is SearchCustomersRequestApplicationJsonPropertySortItemField other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator SearchCustomersRequestApplicationJsonPropertySortItemField(string value) => new(value);
        public static explicit operator string(SearchCustomersRequestApplicationJsonPropertySortItemField value) => value.Value;
        public static bool operator ==(SearchCustomersRequestApplicationJsonPropertySortItemField left, SearchCustomersRequestApplicationJsonPropertySortItemField right) => left.Equals(right);
        public static bool operator !=(SearchCustomersRequestApplicationJsonPropertySortItemField left, SearchCustomersRequestApplicationJsonPropertySortItemField right) => !left.Equals(right);
    }
}
