// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents update referral status response value200 application json property data property commission type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType : ISellAppExtensibleEnum, IEquatable<UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType>
    {
        public UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType Unknown => new("unknown");
        public static UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType Percentage => new("percentage");
        public static UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType Fixed => new("fixed");

        public bool IsKnown => Value is "percentage" or "fixed";
        public bool Equals(UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType(string value) => new(value);
        public static explicit operator string(UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType value) => value.Value;
        public static bool operator ==(UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType left, UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType right) => left.Equals(right);
        public static bool operator !=(UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType left, UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType right) => !left.Equals(right);
    }
}
