// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents update product variant pricing request application json property pricing property frequency interval values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval : ISellAppExtensibleEnum, IEquatable<UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval>
    {
        public UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval Unknown => new("unknown");
        public static UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval Day => new("DAY");
        public static UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval Week => new("WEEK");
        public static UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval Month => new("MONTH");
        public static UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval Year => new("YEAR");

        public bool IsKnown => Value is "DAY" or "WEEK" or "MONTH" or "YEAR";
        public bool Equals(UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval(string value) => new(value);
        public static explicit operator string(UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval value) => value.Value;
        public static bool operator ==(UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval left, UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval right) => left.Equals(right);
        public static bool operator !=(UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval left, UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyFrequencyInterval right) => !left.Equals(right);
    }
}
