// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents update booking configuration response value200 application json property data conflict scope values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope : ISellAppExtensibleEnum, IEquatable<UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope>
    {
        public UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope Unknown => new("unknown");
        public static UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope Product => new("product");
        public static UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope Variant => new("variant");

        public bool IsKnown => Value is "product" or "variant";
        public bool Equals(UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope(string value) => new(value);
        public static explicit operator string(UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope value) => value.Value;
        public static bool operator ==(UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope left, UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope right) => left.Equals(right);
        public static bool operator !=(UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope left, UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataConflictScope right) => !left.Equals(right);
    }
}
