// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents update customer wallet status response value200 application json property data status values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus : ISellAppExtensibleEnum, IEquatable<UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus>
    {
        public UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus Unknown => new("unknown");
        public static UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus Active => new("active");
        public static UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus Frozen => new("frozen");

        public bool IsKnown => Value is "active" or "frozen";
        public bool Equals(UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus(string value) => new(value);
        public static explicit operator string(UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus value) => value.Value;
        public static bool operator ==(UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus left, UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus right) => left.Equals(right);
        public static bool operator !=(UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus left, UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyDataStatus right) => !left.Equals(right);
    }
}
