// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents update wallet bonus tier response value200 application json property data bonus kind values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind : ISellAppExtensibleEnum, IEquatable<UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind>
    {
        public UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind Unknown => new("unknown");
        public static UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind Fixed => new("fixed");
        public static UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind Percent => new("percent");

        public bool IsKnown => Value is "fixed" or "percent";
        public bool Equals(UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind(string value) => new(value);
        public static explicit operator string(UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind value) => value.Value;
        public static bool operator ==(UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind left, UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind right) => left.Equals(right);
        public static bool operator !=(UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind left, UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind right) => !left.Equals(right);
    }
}
