// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents update appointment response value200 application json property data status values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus : ISellAppExtensibleEnum, IEquatable<UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus>
    {
        public UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus Unknown => new("unknown");
        public static UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus Pending => new("pending");
        public static UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus Confirmed => new("confirmed");
        public static UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus Cancelled => new("cancelled");
        public static UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus NeedsReschedule => new("needs_reschedule");
        public static UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus Failed => new("failed");

        public bool IsKnown => Value is "pending" or "confirmed" or "cancelled" or "needs_reschedule" or "failed";
        public bool Equals(UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus(string value) => new(value);
        public static explicit operator string(UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus value) => value.Value;
        public static bool operator ==(UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus left, UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus right) => left.Equals(right);
        public static bool operator !=(UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus left, UpdateAppointmentResponseValue200ApplicationJsonPropertyDataStatus right) => !left.Equals(right);
    }
}
