// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents update course section response value200 application json property data property lessons item property assignment value property questions item question type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType : ISellAppExtensibleEnum, IEquatable<UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType>
    {
        public UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType Unknown => new("unknown");
        public static UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType Text => new("text");
        public static UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType SingleChoice => new("single_choice");
        public static UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType MultipleChoice => new("multiple_choice");

        public bool IsKnown => Value is "text" or "single_choice" or "multiple_choice";
        public bool Equals(UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType(string value) => new(value);
        public static explicit operator string(UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType value) => value.Value;
        public static bool operator ==(UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType left, UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType right) => left.Equals(right);
        public static bool operator !=(UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType left, UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemQuestionType right) => !left.Equals(right);
    }
}
