// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents V2 batch update coupons request application json property resources map value type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType : ISellAppExtensibleEnum, IEquatable<V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType>
    {
        public V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType Unknown => new("unknown");
        public static V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType Percentage => new("PERCENTAGE");
        public static V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType Amount => new("AMOUNT");

        public bool IsKnown => Value is "PERCENTAGE" or "AMOUNT";
        public bool Equals(V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType(string value) => new(value);
        public static explicit operator string(V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType value) => value.Value;
        public static bool operator ==(V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType left, V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType right) => left.Equals(right);
        public static bool operator !=(V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType left, V2BatchUpdateCouponsRequestApplicationJsonPropertyResourcesMapValueType right) => !left.Equals(right);
    }
}
