// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents V2 batch delete coupons response value200 application json property data item type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType : ISellAppExtensibleEnum, IEquatable<V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType>
    {
        public V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType Unknown => new("unknown");
        public static V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType Percentage => new("PERCENTAGE");
        public static V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType Amount => new("AMOUNT");

        public bool IsKnown => Value is "PERCENTAGE" or "AMOUNT";
        public bool Equals(V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType(string value) => new(value);
        public static explicit operator string(V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType value) => value.Value;
        public static bool operator ==(V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType left, V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType right) => left.Equals(right);
        public static bool operator !=(V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType left, V2BatchDeleteCouponsResponseValue200ApplicationJsonPropertyDataItemType right) => !left.Equals(right);
    }
}
