// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents V2 search feedback request application json property filters item type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType : ISellAppExtensibleEnum, IEquatable<V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType>
    {
        public V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType Unknown => new("unknown");
        public static V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType And => new("and");
        public static V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType Or => new("or");

        public bool IsKnown => Value is "and" or "or";
        public bool Equals(V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType(string value) => new(value);
        public static explicit operator string(V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType value) => value.Value;
        public static bool operator ==(V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType left, V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType right) => left.Equals(right);
        public static bool operator !=(V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType left, V2SearchFeedbackRequestApplicationJsonPropertyFiltersItemType right) => !left.Equals(right);
    }
}
