// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents V2 search ticket messages request application json property sort item direction values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection : ISellAppExtensibleEnum, IEquatable<V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection>
    {
        public V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection Unknown => new("unknown");
        public static V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection Asc => new("asc");
        public static V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection Desc => new("desc");

        public bool IsKnown => Value is "asc" or "desc";
        public bool Equals(V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection(string value) => new(value);
        public static explicit operator string(V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection value) => value.Value;
        public static bool operator ==(V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection left, V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection right) => left.Equals(right);
        public static bool operator !=(V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection left, V2SearchTicketMessagesRequestApplicationJsonPropertySortItemDirection right) => !left.Equals(right);
    }
}
