// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents V2 update coupon response value200 application json property data type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType : ISellAppExtensibleEnum, IEquatable<V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType>
    {
        public V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType Unknown => new("unknown");
        public static V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType Percentage => new("PERCENTAGE");
        public static V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType Amount => new("AMOUNT");

        public bool IsKnown => Value is "PERCENTAGE" or "AMOUNT";
        public bool Equals(V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType(string value) => new(value);
        public static explicit operator string(V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType value) => value.Value;
        public static bool operator ==(V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType left, V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType right) => left.Equals(right);
        public static bool operator !=(V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType left, V2UpdateCouponResponseValue200ApplicationJsonPropertyDataType right) => !left.Equals(right);
    }
}
