// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents validate and save payment method configuration response value200 application json property data health status values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus : ISellAppExtensibleEnum, IEquatable<ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus>
    {
        public ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus Unknown => new("unknown");
        public static ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus Disconnected => new("disconnected");
        public static ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus Healthy => new("healthy");
        public static ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus AttentionRequired => new("attention_required");

        public bool IsKnown => Value is "disconnected" or "healthy" or "attention_required";
        public bool Equals(ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus(string value) => new(value);
        public static explicit operator string(ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus value) => value.Value;
        public static bool operator ==(ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus left, ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus right) => left.Equals(right);
        public static bool operator !=(ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus left, ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataHealthStatus right) => !left.Equals(right);
    }
}
