// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents validate and save payment method configuration response value200 application json property data connection type values.</summary>
    [JsonConverter(typeof(SellAppNewtonsoftStringEnumConverter))]
    [STJS.JsonConverter(typeof(SellAppStringEnumConverterFactory))]
    public readonly struct ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType : ISellAppExtensibleEnum, IEquatable<ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType>
    {
        public ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType(string value)
        {
            Value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public string Value { get; }

        public static ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType Unknown => new("unknown");
        public static ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType OAuth => new("oauth");
        public static ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType ApiKeys => new("api_keys");
        public static ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType Wallet => new("wallet");
        public static ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType Custom => new("custom");

        public bool IsKnown => Value is "oauth" or "api_keys" or "wallet" or "custom";
        public bool Equals(ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType other) => StringComparer.Ordinal.Equals(Value, other.Value);
        public override bool Equals(object? obj) => obj is ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType other && Equals(other);
        public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Value ?? string.Empty);
        public override string ToString() => Value ?? string.Empty;
        public static implicit operator ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType(string value) => new(value);
        public static explicit operator string(ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType value) => value.Value;
        public static bool operator ==(ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType left, ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType right) => left.Equals(right);
        public static bool operator !=(ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType left, ValidateAndSavePaymentMethodConfigurationResponseValue200ApplicationJsonPropertyDataConnectionType right) => !left.Equals(right);
    }
}
