// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the tickets messages API operations on <see cref="SellAppClient"/>.</summary>
    public class TicketsMessagesService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TicketsMessagesService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="SellAppConfiguration.SellAppClient"/>.
        /// </summary>
        public TicketsMessagesService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="TicketsMessagesService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public TicketsMessagesService(SellAppClient client) : base(client) { }

        /// <summary>List all ticket messages</summary>
        /// <remarks>
        /// Read a ticket's conversation, 15 messages per page by default.
        /// </remarks>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem"/> results.</returns>
        public virtual async Task<SellAppList<ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>> ListAsync(string ticket, TicketsMessagesListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "listTicketMessages", false);
            return await this.GetAsync<SellAppList<ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>>($"/v1/tickets/{Uri.EscapeDataString(ticket)}/messages", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SellAppList<ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>>> ListWithResponseAsync(string ticket, TicketsMessagesListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.ListAsync(ticket, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="ListAsync"/>.</summary>
        public virtual Task<SellAppList<ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>> List(string ticket, TicketsMessagesListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ListAsync(ticket, options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="ListAsync"/>. Yields individual items across all pages.</summary>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem"/> items.</returns>
        public virtual IAsyncEnumerable<ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem> ListAutoPagingAsync(string ticket, TicketsMessagesListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "listTicketMessages", false);
            return base.ListAutoPagingAsync<ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>(HttpMethod.Get, $"/v1/tickets/{Uri.EscapeDataString(ticket)}/messages", options, requestOptions, cancellationToken);
        }

        /// <summary>Reply to ticket</summary>
        /// <remarks>
        /// Add a seller reply to a support conversation.
        /// </remarks>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkReplyToTicketResponseValue201ApplicationJson"/> result.</returns>
        public virtual async Task<SdkReplyToTicketResponseValue201ApplicationJson> ReplyAsync(string ticket, TicketsMessagesReplyOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "replyToTicket", false);
            return await this.PostAsync<SdkReplyToTicketResponseValue201ApplicationJson>($"/v1/tickets/{Uri.EscapeDataString(ticket)}/messages", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkReplyToTicketResponseValue201ApplicationJson>> ReplyWithResponseAsync(string ticket, TicketsMessagesReplyOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.ReplyAsync(ticket, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="ReplyAsync"/>.</summary>
        public virtual Task<SdkReplyToTicketResponseValue201ApplicationJson> Reply(string ticket, TicketsMessagesReplyOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ReplyAsync(ticket, options, requestOptions, cancellationToken);
        }

        /// <summary>Retrieve specific ticket message</summary>
        /// <remarks>
        /// Retrieve one message using its ticket ID and message ID.
        /// </remarks>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="message">The message path parameter.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkGetTicketMessageResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkGetTicketMessageResponseValue200ApplicationJson> GetAsync(string ticket, string message, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "getTicketMessage", false);
            return await this.GetAsync<SdkGetTicketMessageResponseValue200ApplicationJson>($"/v1/tickets/{Uri.EscapeDataString(ticket)}/messages/{Uri.EscapeDataString(message)}", null, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkGetTicketMessageResponseValue200ApplicationJson>> GetWithResponseAsync(string ticket, string message, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.GetAsync(ticket, message, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="GetAsync"/>.</summary>
        public virtual Task<SdkGetTicketMessageResponseValue200ApplicationJson> Get(string ticket, string message, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.GetAsync(ticket, message, requestOptions, cancellationToken);
        }

        /// <summary>Search ticket messages</summary>
        /// <remarks>
        /// Search a ticket's messages using JSON body filters, search terms, includes, and sort instructions.
        /// </remarks>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem"/> results.</returns>
        public virtual async Task<SellAppList<SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>> SearchAsync(string ticket, TicketsMessagesSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "searchTicketMessages", false);
            return await this.PostAsync<SellAppList<SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>>($"/v1/tickets/{Uri.EscapeDataString(ticket)}/messages/search", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SellAppList<SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>>> SearchWithResponseAsync(string ticket, TicketsMessagesSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.SearchAsync(ticket, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="SearchAsync"/>.</summary>
        public virtual Task<SellAppList<SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>> Search(string ticket, TicketsMessagesSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.SearchAsync(ticket, options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="SearchAsync"/>. Yields individual items across all pages.</summary>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem"/> items.</returns>
        public virtual IAsyncEnumerable<SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem> SearchAutoPagingAsync(string ticket, TicketsMessagesSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "searchTicketMessages", false);
            return base.ListAutoPagingAsync<SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>(HttpMethod.Post, $"/v1/tickets/{Uri.EscapeDataString(ticket)}/messages/search", options, requestOptions, cancellationToken);
        }

        /// <summary>List all ticket messages</summary>
        /// <remarks>
        /// Read a ticket's conversation, 15 messages per page by default. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="V2ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem"/> results.</returns>
        public virtual async Task<SellAppList<V2ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>> V2ListTicketMessagesAsync(string ticket, TicketsMessagesV2ListTicketMessagesOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "v2ListTicketMessages", false);
            return await this.GetAsync<SellAppList<V2ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>>($"/v2/tickets/{Uri.EscapeDataString(ticket)}/messages", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SellAppList<V2ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>>> V2ListTicketMessagesWithResponseAsync(string ticket, TicketsMessagesV2ListTicketMessagesOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.V2ListTicketMessagesAsync(ticket, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="V2ListTicketMessagesAsync"/>.</summary>
        public virtual Task<SellAppList<V2ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>> V2ListTicketMessages(string ticket, TicketsMessagesV2ListTicketMessagesOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.V2ListTicketMessagesAsync(ticket, options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="V2ListTicketMessagesAsync"/>. Yields individual items across all pages.</summary>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="V2ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem"/> items.</returns>
        public virtual IAsyncEnumerable<V2ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem> V2ListTicketMessagesAutoPagingAsync(string ticket, TicketsMessagesV2ListTicketMessagesOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "v2ListTicketMessages", false);
            return base.ListAutoPagingAsync<V2ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>(HttpMethod.Get, $"/v2/tickets/{Uri.EscapeDataString(ticket)}/messages", options, requestOptions, cancellationToken);
        }

        /// <summary>Reply to ticket</summary>
        /// <remarks>
        /// Add a seller reply to a support conversation. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkV2ReplyToTicketResponseValue201ApplicationJson"/> result.</returns>
        public virtual async Task<SdkV2ReplyToTicketResponseValue201ApplicationJson> V2ReplyToTicketAsync(string ticket, TicketsMessagesV2ReplyToTicketOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "v2ReplyToTicket", false);
            return await this.PostAsync<SdkV2ReplyToTicketResponseValue201ApplicationJson>($"/v2/tickets/{Uri.EscapeDataString(ticket)}/messages", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkV2ReplyToTicketResponseValue201ApplicationJson>> V2ReplyToTicketWithResponseAsync(string ticket, TicketsMessagesV2ReplyToTicketOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.V2ReplyToTicketAsync(ticket, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="V2ReplyToTicketAsync"/>.</summary>
        public virtual Task<SdkV2ReplyToTicketResponseValue201ApplicationJson> V2ReplyToTicket(string ticket, TicketsMessagesV2ReplyToTicketOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.V2ReplyToTicketAsync(ticket, options, requestOptions, cancellationToken);
        }

        /// <summary>Search ticket messages</summary>
        /// <remarks>
        /// Search a ticket's messages using JSON body filters, search terms, includes, and sort instructions. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem"/> results.</returns>
        public virtual async Task<SellAppList<V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>> V2SearchTicketMessagesAsync(string ticket, TicketsMessagesV2SearchTicketMessagesOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "v2SearchTicketMessages", false);
            return await this.PostAsync<SellAppList<V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>>($"/v2/tickets/{Uri.EscapeDataString(ticket)}/messages/search", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SellAppList<V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>>> V2SearchTicketMessagesWithResponseAsync(string ticket, TicketsMessagesV2SearchTicketMessagesOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.V2SearchTicketMessagesAsync(ticket, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="V2SearchTicketMessagesAsync"/>.</summary>
        public virtual Task<SellAppList<V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>> V2SearchTicketMessages(string ticket, TicketsMessagesV2SearchTicketMessagesOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.V2SearchTicketMessagesAsync(ticket, options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="V2SearchTicketMessagesAsync"/>. Yields individual items across all pages.</summary>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem"/> items.</returns>
        public virtual IAsyncEnumerable<V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem> V2SearchTicketMessagesAutoPagingAsync(string ticket, TicketsMessagesV2SearchTicketMessagesOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "v2SearchTicketMessages", false);
            return base.ListAutoPagingAsync<V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>(HttpMethod.Post, $"/v2/tickets/{Uri.EscapeDataString(ticket)}/messages/search", options, requestOptions, cancellationToken);
        }

        /// <summary>Retrieve specific ticket message</summary>
        /// <remarks>
        /// Retrieve one message using its ticket ID and message ID. This v2 route is store-scoped. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="ticket">The ticket path parameter.</param>
        /// <param name="message">The message path parameter.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkV2GetTicketMessageResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkV2GetTicketMessageResponseValue200ApplicationJson> V2GetTicketMessageAsync(string ticket, string message, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "v2GetTicketMessage", false);
            return await this.GetAsync<SdkV2GetTicketMessageResponseValue200ApplicationJson>($"/v2/tickets/{Uri.EscapeDataString(ticket)}/messages/{Uri.EscapeDataString(message)}", null, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkV2GetTicketMessageResponseValue200ApplicationJson>> V2GetTicketMessageWithResponseAsync(string ticket, string message, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.V2GetTicketMessageAsync(ticket, message, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="V2GetTicketMessageAsync"/>.</summary>
        public virtual Task<SdkV2GetTicketMessageResponseValue200ApplicationJson> V2GetTicketMessage(string ticket, string message, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.V2GetTicketMessageAsync(ticket, message, requestOptions, cancellationToken);
        }
    }
}
