// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the products addons API operations on <see cref="SellAppClient"/>.</summary>
    public class ProductsAddonsService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductsAddonsService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="SellAppConfiguration.SellAppClient"/>.
        /// </summary>
        public ProductsAddonsService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductsAddonsService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public ProductsAddonsService(SellAppClient client) : base(client) { }

        /// <summary>List a product's add-ons</summary>
        /// <remarks>
        /// Retrieve the ordered add-ons assigned to a product, course, or booking. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="SdkListProductSAddOnsResponseValue200ApplicationJson"/> results.</returns>
        public virtual async Task<SellAppList<SdkListProductSAddOnsResponseValue200ApplicationJson>> ListAsync(string product, ProductsAddonsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "listProductSAddOns", false);
            return await this.GetAsync<SellAppList<SdkListProductSAddOnsResponseValue200ApplicationJson>>($"/v2/products/{Uri.EscapeDataString(product)}/addons", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SellAppList<SdkListProductSAddOnsResponseValue200ApplicationJson>>> ListWithResponseAsync(string product, ProductsAddonsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.ListAsync(product, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="ListAsync"/>.</summary>
        public virtual Task<SellAppList<SdkListProductSAddOnsResponseValue200ApplicationJson>> List(string product, ProductsAddonsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ListAsync(product, options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="ListAsync"/>. Yields individual items across all pages.</summary>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="SdkListProductSAddOnsResponseValue200ApplicationJson"/> items.</returns>
        public virtual IAsyncEnumerable<SdkListProductSAddOnsResponseValue200ApplicationJson> ListAutoPagingAsync(string product, ProductsAddonsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "listProductSAddOns", false);
            return base.ListAutoPagingAsync<SdkListProductSAddOnsResponseValue200ApplicationJson>(HttpMethod.Get, $"/v2/products/{Uri.EscapeDataString(product)}/addons", options, requestOptions, cancellationToken);
        }

        /// <summary>Replace a product's add-ons</summary>
        /// <remarks>
        /// Replace the complete ordered add-on assignment for a non-subscription product, course, or booking. Newly assigned add-ons must be published, public, and owned by the same store; already assigned non-public add-ons may be retained for safe editing. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkReplaceProductSAddOnsResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkReplaceProductSAddOnsResponseValue200ApplicationJson> ReplaceAsync(string product, ProductsAddonsReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "replaceProductSAddOns", false);
            return await this.PutAsync<SdkReplaceProductSAddOnsResponseValue200ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/addons", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkReplaceProductSAddOnsResponseValue200ApplicationJson>> ReplaceWithResponseAsync(string product, ProductsAddonsReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.ReplaceAsync(product, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="ReplaceAsync"/>.</summary>
        public virtual Task<SdkReplaceProductSAddOnsResponseValue200ApplicationJson> Replace(string product, ProductsAddonsReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ReplaceAsync(product, options, requestOptions, cancellationToken);
        }
    }
}
