// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the product variants booking API operations on <see cref="SellAppClient"/>.</summary>
    public class ProductVariantsBookingService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductVariantsBookingService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="SellAppConfiguration.SellAppClient"/>.
        /// </summary>
        public ProductVariantsBookingService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductVariantsBookingService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public ProductVariantsBookingService(SellAppClient client) : base(client) { }

        /// <summary>List booking availability</summary>
        /// <remarks>
        /// Retrieve available appointment slots for a booking product variant. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="variant">The variant path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkListBookingAvailabilityResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkListBookingAvailabilityResponseValue200ApplicationJson> ListAvailabilityAsync(string product, string variant, ProductVariantsBookingListAvailabilityOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "listBookingAvailability", false);
            return await this.GetAsync<SdkListBookingAvailabilityResponseValue200ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants/{Uri.EscapeDataString(variant)}/booking/availability", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkListBookingAvailabilityResponseValue200ApplicationJson>> ListAvailabilityWithResponseAsync(string product, string variant, ProductVariantsBookingListAvailabilityOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.ListAvailabilityAsync(product, variant, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="ListAvailabilityAsync"/>.</summary>
        public virtual Task<SdkListBookingAvailabilityResponseValue200ApplicationJson> ListAvailability(string product, string variant, ProductVariantsBookingListAvailabilityOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ListAvailabilityAsync(product, variant, options, requestOptions, cancellationToken);
        }

        /// <summary>Create a booking hold</summary>
        /// <remarks>
        /// Temporarily reserve a booking slot before checkout. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="variant">The variant path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkCreateBookingHoldResponseValue201ApplicationJson"/> result.</returns>
        public virtual async Task<SdkCreateBookingHoldResponseValue201ApplicationJson> CreateHoldAsync(string product, string variant, ProductVariantsBookingCreateHoldOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "createBookingHold", false);
            return await this.PostAsync<SdkCreateBookingHoldResponseValue201ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants/{Uri.EscapeDataString(variant)}/booking/holds", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkCreateBookingHoldResponseValue201ApplicationJson>> CreateHoldWithResponseAsync(string product, string variant, ProductVariantsBookingCreateHoldOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.CreateHoldAsync(product, variant, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="CreateHoldAsync"/>.</summary>
        public virtual Task<SdkCreateBookingHoldResponseValue201ApplicationJson> CreateHold(string product, string variant, ProductVariantsBookingCreateHoldOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.CreateHoldAsync(product, variant, options, requestOptions, cancellationToken);
        }

        /// <summary>Release a booking hold</summary>
        /// <remarks>
        /// Release a previously created booking hold. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="hold">The hold path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        public virtual async Task ReleaseHoldAsync(string product, string hold, ProductVariantsBookingReleaseHoldOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "releaseBookingHold", false);
            await this.DeleteAsync($"/v2/products/{Uri.EscapeDataString(product)}/variants/booking/holds/{Uri.EscapeDataString(hold)}", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<object?>> ReleaseHoldWithResponseAsync(string product, string hold, ProductVariantsBookingReleaseHoldOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            await this.ReleaseHoldAsync(product, hold, options, requestOptions, cancellationToken);
            return capture.Wrap<object?>(null);
        }

        /// <summary>Compatibility wrapper for <see cref="ReleaseHoldAsync"/>.</summary>
        public virtual Task ReleaseHold(string product, string hold, ProductVariantsBookingReleaseHoldOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ReleaseHoldAsync(product, hold, options, requestOptions, cancellationToken);
        }

        /// <summary>Retrieve booking configuration</summary>
        /// <remarks>
        /// Retrieve creator-facing availability, capacity, calendar, meeting, and reminder configuration for a booking variant. Requires the `listing` Sanctum ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The booking product ID or slug.</param>
        /// <param name="variant">The variant path parameter.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkGetBookingConfigurationResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkGetBookingConfigurationResponseValue200ApplicationJson> GetAsync(string product, string variant, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "getBookingConfiguration", false);
            return await this.GetAsync<SdkGetBookingConfigurationResponseValue200ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants/{Uri.EscapeDataString(variant)}/booking", null, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkGetBookingConfigurationResponseValue200ApplicationJson>> GetWithResponseAsync(string product, string variant, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.GetAsync(product, variant, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="GetAsync"/>.</summary>
        public virtual Task<SdkGetBookingConfigurationResponseValue200ApplicationJson> Get(string product, string variant, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.GetAsync(product, variant, requestOptions, cancellationToken);
        }

        /// <summary>Update booking configuration</summary>
        /// <remarks>
        /// Partially update a booking variant's configuration. Provider connection IDs must belong to the selected store; secret credentials are never accepted or returned here. Requires the `listing` Sanctum ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The booking product ID or slug.</param>
        /// <param name="variant">The variant path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkReplaceBookingConfigurationResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkReplaceBookingConfigurationResponseValue200ApplicationJson> ReplaceAsync(string product, string variant, ProductVariantsBookingReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "replaceBookingConfiguration", false);
            return await this.PutAsync<SdkReplaceBookingConfigurationResponseValue200ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants/{Uri.EscapeDataString(variant)}/booking", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkReplaceBookingConfigurationResponseValue200ApplicationJson>> ReplaceWithResponseAsync(string product, string variant, ProductVariantsBookingReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.ReplaceAsync(product, variant, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="ReplaceAsync"/>.</summary>
        public virtual Task<SdkReplaceBookingConfigurationResponseValue200ApplicationJson> Replace(string product, string variant, ProductVariantsBookingReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ReplaceAsync(product, variant, options, requestOptions, cancellationToken);
        }

        /// <summary>Update booking configuration</summary>
        /// <remarks>
        /// Partially update a booking variant's configuration. Provider connection IDs must belong to the selected store; secret credentials are never accepted or returned here. Requires the `listing` Sanctum ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The booking product ID or slug.</param>
        /// <param name="variant">The variant path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkUpdateBookingConfigurationResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkUpdateBookingConfigurationResponseValue200ApplicationJson> UpdateAsync(string product, string variant, ProductVariantsBookingUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "updateBookingConfiguration", false);
            return await this.PatchAsync<SdkUpdateBookingConfigurationResponseValue200ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants/{Uri.EscapeDataString(variant)}/booking", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkUpdateBookingConfigurationResponseValue200ApplicationJson>> UpdateWithResponseAsync(string product, string variant, ProductVariantsBookingUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.UpdateAsync(product, variant, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="UpdateAsync"/>.</summary>
        public virtual Task<SdkUpdateBookingConfigurationResponseValue200ApplicationJson> Update(string product, string variant, ProductVariantsBookingUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.UpdateAsync(product, variant, options, requestOptions, cancellationToken);
        }
    }
}
