// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="CreditsBalancesTransactionsService.ListAsync"/>: List credit balance transactions</summary>
    [SellAppModelSchema(false)]
    public class CreditsBalancesTransactionsListOptions : ListOptions
    {
        [JsonProperty("page")]
        [STJS.JsonPropertyName("page")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? Page { get; set; }

    }
}
