// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="PaymentMethodsService.EnableAsync"/>: Enable or disable a payment method</summary>
    [SellAppModelSchema(false)]
    public class PaymentMethodsEnableOptions : BaseOptions
    {
        [JsonProperty("enabled", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

    }

    /// <summary>Request options for <see cref="PaymentMethodsService.ValidateAsync"/>: Validate and save payment method configuration</summary>
    [SellAppModelSchema(false)]
    public class PaymentMethodsValidateOptions : BaseOptions, IUnionRequestOptions
    {
        public OneOf.OneOf<ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue1, OneOf.OneOf<ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue2, OneOf.OneOf<ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue3, OneOf.OneOf<ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue4, OneOf.OneOf<ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue5, ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue6>>>>> Body { get; set; } = default!;
        object IUnionRequestOptions.RequestBody => Body;
    }
}
