// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a batch delete sections response value200 application json property data item property groups item.</summary>
    [SellAppModelSchema(true)]
    public class BatchDeleteSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItem
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public long Id { get; set; }
        [JsonProperty("title", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("title")]
        public string Title { get; set; } = default!;
        [JsonProperty("group_products", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("group_products")]
        public long GroupProducts { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
