// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a batch update product variants request application json property resources map value property pricing.</summary>
    [SellAppModelSchema(true)]
    public class BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyPricing
    {
        [JsonProperty("humble", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("humble")]
        public bool Humble { get; set; }
        [JsonProperty("price", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("price")]
        public BatchUpdateProductVariantsRequestApplicationJsonPropertyResourcesMapValuePropertyPricingPropertyPrice Price { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
