// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a create product request application json property bundle items item.</summary>
    [SellAppModelSchema(false)]
    public class CreateProductRequestApplicationJsonPropertyBundleItemsItem
    {
        [JsonProperty("product_variant_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("product_variant_id")]
        public long ProductVariantId { get; set; }
        [JsonProperty("quantity", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("quantity")]
        [SellAppSchemaConstraints(Minimum = 1d, Maximum = 2147483647d)]
        public long Quantity { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
