// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a create notification channel request application json property channel one of value2.</summary>
    [SellAppModelSchema(true)]
    public class CreateNotificationChannelRequestApplicationJsonPropertyChannelOneOfValue2
    {
        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("type")]
        public string Type { get; internal set; } = "discord";
        [JsonProperty("channel", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("channel")]
        public string Channel { get; set; } = default!;
        [JsonProperty("webhook", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("webhook")]
        public string Webhook { get; set; } = default!;
        [JsonProperty("allowed_notifications", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("allowed_notifications")]
        public List<string> AllowedNotifications { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
