// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a create customer session response value201 application json property data.</summary>
    [SellAppModelSchema(true)]
    public class CreateCustomerSessionResponseValue201ApplicationJsonPropertyData
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        [JsonProperty("token", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("token")]
        public string Token { get; set; } = default!;
        [JsonProperty("redemption_url", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("redemption_url")]
        public string RedemptionUrl { get; set; } = default!;
        [JsonProperty("expires_at", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("expires_at")]
        public DateTimeOffset ExpiresAt { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
