// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a create fulfillment retry response value200 application json property data.</summary>
    [SellAppModelSchema(true)]
    public class CreateFulfillmentRetryResponseValue200ApplicationJsonPropertyData
    {
        [JsonProperty("effects_reset", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("effects_reset")]
        public long EffectsReset { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
