// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a create checkout session response value201 application json property invoice property status.</summary>
    [SellAppModelSchema(true)]
    public class CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyStatus
    {
        [JsonProperty("history", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("history")]
        public List<string> History { get; set; } = default!;
        [JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("status")]
        public CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyStatusPropertyStatus Status { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
