// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a create product request application json property variants item property deliverable property data property booking.</summary>
    [SellAppModelSchema(true)]
    public class CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBooking
    {
        [JsonProperty("mode")]
        [STJS.JsonPropertyName("mode")]
        public string? Mode { get; set; }
        [JsonProperty("conflict_scope")]
        [STJS.JsonPropertyName("conflict_scope")]
        public CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBookingConflictScope? ConflictScope { get; set; }
        [JsonProperty("timezone")]
        [STJS.JsonPropertyName("timezone")]
        public string? Timezone { get; set; }
        [JsonProperty("duration_minutes")]
        [STJS.JsonPropertyName("duration_minutes")]
        [SellAppSchemaConstraints(Minimum = 30d, MultipleOf = 30d)]
        public long? DurationMinutes { get; set; }
        [JsonProperty("capacity_per_slot")]
        [STJS.JsonPropertyName("capacity_per_slot")]
        [SellAppSchemaConstraints(Minimum = 1d, Maximum = 1000d)]
        public long? CapacityPerSlot { get; set; }
        [JsonProperty("min_notice_minutes")]
        [STJS.JsonPropertyName("min_notice_minutes")]
        [SellAppSchemaConstraints(Minimum = 0d, Maximum = 525600d)]
        public long? MinNoticeMinutes { get; set; }
        [JsonProperty("max_advance_days")]
        [STJS.JsonPropertyName("max_advance_days")]
        [SellAppSchemaConstraints(Minimum = 1d, Maximum = 730d)]
        public long? MaxAdvanceDays { get; set; }
        [JsonProperty("buffer_before_minutes")]
        [STJS.JsonPropertyName("buffer_before_minutes")]
        [SellAppSchemaConstraints(Minimum = 0d, Maximum = 1440d, MultipleOf = 30d)]
        public long? BufferBeforeMinutes { get; set; }
        [JsonProperty("buffer_after_minutes")]
        [STJS.JsonPropertyName("buffer_after_minutes")]
        [SellAppSchemaConstraints(Minimum = 0d, Maximum = 1440d, MultipleOf = 30d)]
        public long? BufferAfterMinutes { get; set; }
        [JsonProperty("availability")]
        [STJS.JsonPropertyName("availability")]
        [SellAppSchemaConstraints(MinItems = 7, MaxItems = 7)]
        public List<CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBookingPropertyAvailabilityItem>? Availability { get; set; }
        [JsonProperty("provider_connection_ids")]
        [STJS.JsonPropertyName("provider_connection_ids")]
        public List<long>? ProviderConnectionIds { get; set; }
        [JsonProperty("video_provider")]
        [STJS.JsonPropertyName("video_provider")]
        public CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBookingVideoProvider? VideoProvider { get; set; }
        [JsonProperty("video_provider_connection_id")]
        [STJS.JsonPropertyName("video_provider_connection_id")]
        public long? VideoProviderConnectionId { get; set; }
        [JsonProperty("reminders_enabled")]
        [STJS.JsonPropertyName("reminders_enabled")]
        public bool? RemindersEnabled { get; set; }
        [JsonProperty("reminder_offset_value")]
        [STJS.JsonPropertyName("reminder_offset_value")]
        [SellAppSchemaConstraints(Minimum = 1d, Maximum = 10080d)]
        public long? ReminderOffsetValue { get; set; }
        [JsonProperty("reminder_offset_unit")]
        [STJS.JsonPropertyName("reminder_offset_unit")]
        public CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit? ReminderOffsetUnit { get; set; }
        [JsonProperty("meta")]
        [STJS.JsonPropertyName("meta")]
        public CreateProductRequestApplicationJsonPropertyVariantsItemPropertyDeliverablePropertyDataPropertyBookingPropertyMeta? Meta { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
