// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a create product request application json property variants item property bulk discount item.</summary>
    [SellAppModelSchema(true)]
    public class CreateProductRequestApplicationJsonPropertyVariantsItemPropertyBulkDiscountItem
    {
        [JsonProperty("minimum_purchase_amount", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("minimum_purchase_amount")]
        public long MinimumPurchaseAmount { get; set; }
        [JsonProperty("discount_percentage", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("discount_percentage")]
        public long DiscountPercentage { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
