// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a create product variant response value201 application json property data property deliverable.</summary>
    [SellAppModelSchema(true)]
    public class CreateProductVariantResponseValue201ApplicationJsonPropertyDataPropertyDeliverable
    {
        [JsonProperty("data", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("data")]
        public CreateProductVariantResponseValue201ApplicationJsonPropertyDataPropertyDeliverablePropertyData Data { get; set; } = default!;
        [JsonProperty("types", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("types")]
        public List<string> Types { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
