// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a get course response value200 application json property data property sections item property lessons item property assignment.</summary>
    [SellAppModelSchema(true)]
    public class GetCourseResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemPropertyAssignment
    {
        [JsonProperty("estimated_duration_minutes", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("estimated_duration_minutes")]
        [SellAppSchemaConstraints(Minimum = 1d, Maximum = 1440d)]
        public long? EstimatedDurationMinutes { get; set; }
        [JsonProperty("instructions", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("instructions")]
        public string? Instructions { get; set; }
        [JsonProperty("questions", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("questions")]
        public List<GetCourseResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItem> Questions { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
