// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a get credit balance response value200 application json property data.</summary>
    [SellAppModelSchema(true)]
    public class GetCreditBalanceResponseValue200ApplicationJsonPropertyData
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public long Id { get; set; }
        [JsonProperty("store_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("store_id")]
        public long StoreId { get; set; }
        [JsonProperty("customer_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("customer_id")]
        public long CustomerId { get; set; }

        /// <summary>The email of the customer holding the balance, or null once the customer is deleted.</summary>
        [JsonProperty("customer_email")]
        [STJS.JsonPropertyName("customer_email")]
        public string? CustomerEmail { get; set; }
        [JsonProperty("product_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("product_id")]
        public long ProductId { get; set; }

        /// <summary>The title of the credits product, or null once the product is soft-deleted.</summary>
        [JsonProperty("product_title")]
        [STJS.JsonPropertyName("product_title")]
        public string? ProductTitle { get; set; }
        [JsonProperty("balance_units", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("balance_units")]
        [SellAppSchemaConstraints(Minimum = 0d)]
        public long BalanceUnits { get; set; }
        [JsonProperty("ledger_entries")]
        [STJS.JsonPropertyName("ledger_entries")]
        public List<GetCreditBalanceResponseValue200ApplicationJsonPropertyDataPropertyLedgerEntriesItem>? LedgerEntries { get; set; }
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset? CreatedAt { get; set; }
        [JsonProperty("updated_at")]
        [STJS.JsonPropertyName("updated_at")]
        public DateTimeOffset? UpdatedAt { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
