// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a get credits product response value200 application json property data.</summary>
    [SellAppModelSchema(true)]
    public class GetCreditsProductResponseValue200ApplicationJsonPropertyData
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public long Id { get; set; }
        [JsonProperty("store_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("store_id")]
        public long StoreId { get; set; }
        [JsonProperty("title", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("title")]
        public string Title { get; set; } = default!;
        [JsonProperty("slug", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("slug")]
        public string Slug { get; set; } = default!;
        [JsonProperty("description")]
        [STJS.JsonPropertyName("description")]
        public string? Description { get; set; }
        [JsonProperty("visibility", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("visibility")]
        public CatalogVisibility Visibility { get; set; }
        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("type")]
        public string Type { get; internal set; } = "credits";
        [JsonProperty("is_draft", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("is_draft")]
        public bool IsDraft { get; set; }
        [JsonProperty("is_discoverable", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("is_discoverable")]
        public bool IsDiscoverable { get; set; }
        [JsonProperty("section_id")]
        [STJS.JsonPropertyName("section_id")]
        public long? SectionId { get; set; }
        [JsonProperty("default_variant", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("default_variant")]
        public GetCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyDefaultVariant? DefaultVariant { get; set; }
        [JsonProperty("variant_invariant")]
        [STJS.JsonPropertyName("variant_invariant")]
        public GetCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyVariantInvariant? VariantInvariant { get; set; }
        [JsonProperty("created_at")]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset? CreatedAt { get; set; }
        [JsonProperty("updated_at")]
        [STJS.JsonPropertyName("updated_at")]
        public DateTimeOffset? UpdatedAt { get; set; }
        [JsonProperty("deleted_at")]
        [STJS.JsonPropertyName("deleted_at")]
        public DateTimeOffset? DeletedAt { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
