// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a get invoice response value200 application json property data property payment.</summary>
    [SellAppModelSchema(true)]
    public class GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPayment
    {
        [JsonProperty("fee", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("fee")]
        public GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyFee Fee { get; set; } = default!;
        [JsonProperty("gateway", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("gateway")]
        public GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyGateway Gateway { get; set; } = default!;
        [JsonProperty("subtotal", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("subtotal")]
        public GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal Subtotal { get; set; } = default!;
        [JsonProperty("expires_at", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("expires_at")]
        public DateTimeOffset ExpiresAt { get; set; }
        [JsonProperty("full_price", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("full_price")]
        public GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyFullPrice FullPrice { get; set; } = default!;
        [JsonProperty("original_amount", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("original_amount")]
        public GetInvoiceResponseValue200ApplicationJsonPropertyDataPropertyPaymentPropertyOriginalAmount OriginalAmount { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
