// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a get order s line item response value200 application json property data.</summary>
    [SellAppModelSchema(true)]
    public class GetOrderSLineItemResponseValue200ApplicationJsonPropertyData
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public long Id { get; set; }
        [JsonProperty("order", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("order")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyOrder Order { get; set; } = default!;
        [JsonProperty("status", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("status")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataStatus Status { get; set; }
        [JsonProperty("product", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("product")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyProduct Product { get; set; } = default!;
        [JsonProperty("variant", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("variant")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyVariant Variant { get; set; } = default!;

        /// <summary>The customer ID when the referenced customer belongs to the authenticated store; otherwise null.</summary>
        [JsonProperty("customer_id")]
        [STJS.JsonPropertyName("customer_id")]
        public long? CustomerId { get; set; }
        [JsonProperty("quantity", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("quantity")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long Quantity { get; set; }
        [JsonProperty("currency", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("currency")]
        [SellAppSchemaConstraints(MinLength = 3, MaxLength = 3)]
        public string? Currency { get; set; }
        [JsonProperty("currency_rate")]
        [STJS.JsonPropertyName("currency_rate")]
        public string? CurrencyRate { get; set; }
        [JsonProperty("payment_method")]
        [STJS.JsonPropertyName("payment_method")]
        public PaymentMethod? PaymentMethod { get; set; }
        [JsonProperty("amounts", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("amounts")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyAmounts Amounts { get; set; } = default!;
        [JsonProperty("discounts", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("discounts")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscounts Discounts { get; set; } = default!;
        [JsonProperty("tax", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("tax")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyTax Tax { get; set; } = default!;
        [JsonProperty("promotion", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("promotion")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyPromotion? Promotion { get; set; }
        [JsonProperty("referral", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("referral")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyReferral? Referral { get; set; }
        [JsonProperty("subscription", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("subscription")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertySubscription? Subscription { get; set; }
        [JsonProperty("fulfillment", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("fulfillment")]
        public GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyFulfillment Fulfillment { get; set; } = default!;
        [JsonProperty("created_at", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset? CreatedAt { get; set; }
        [JsonProperty("updated_at", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("updated_at")]
        public DateTimeOffset? UpdatedAt { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
