// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an issue replacement for completed invoice response value200 application json property customer information property discord data.</summary>
    [SellAppModelSchema(true)]
    public class IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyCustomerInformationPropertyDiscordData
    {

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
