// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an issue replacement for completed invoice response value200 application json property payment property gateway.</summary>
    [SellAppModelSchema(true)]
    public class IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGateway
    {
        [JsonProperty("data", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("data")]
        public IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyPaymentPropertyGatewayPropertyData Data { get; set; } = default!;
        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("type")]
        public string Type { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
