// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a list products within group response value200 application json property data item property pivot.</summary>
    [SellAppModelSchema(true)]
    public class ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemPropertyPivot
    {
        [JsonProperty("group_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("group_id")]
        public long GroupId { get; set; }
        [JsonProperty("listing_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("listing_id")]
        public long ListingId { get; set; }
        [JsonProperty("order", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("order")]
        public long Order { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
