// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a list booking availability response value200 application json property data item.</summary>
    [SellAppModelSchema(true)]
    public class ListBookingAvailabilityResponseValue200ApplicationJsonPropertyDataItem
    {
        [JsonProperty("start", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("start")]
        public DateTimeOffset Start { get; set; }
        [JsonProperty("end", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("end")]
        public DateTimeOffset End { get; set; }
        [JsonProperty("label", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("label")]
        public string Label { get; set; } = default!;
        [JsonProperty("timezone", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("timezone")]
        public string Timezone { get; set; } = default!;
        [JsonProperty("available_capacity", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("available_capacity")]
        public long AvailableCapacity { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
