// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Line-item accounting values. All integer amounts are minor currency units. USD-suffixed values are US dollar cents.</summary>
    [SellAppModelSchema(true)]
    public class ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyAmounts
    {

        /// <summary>The historical decimal unit-price snapshot stored for the line item.</summary>
        [JsonProperty("unit_price", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("unit_price")]
        public string? UnitPrice { get; set; }
        [JsonProperty("subtotal_cents", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("subtotal_cents")]
        public long? SubtotalCents { get; set; }
        [JsonProperty("credit_cents")]
        [STJS.JsonPropertyName("credit_cents")]
        public long? CreditCents { get; set; }
        [JsonProperty("total_exclusive_cents")]
        [STJS.JsonPropertyName("total_exclusive_cents")]
        public long? TotalExclusiveCents { get; set; }
        [JsonProperty("total_exclusive_usd_cents")]
        [STJS.JsonPropertyName("total_exclusive_usd_cents")]
        public long? TotalExclusiveUsdCents { get; set; }
        [JsonProperty("total_cents", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("total_cents")]
        public long TotalCents { get; set; }
        [JsonProperty("total_usd_cents")]
        [STJS.JsonPropertyName("total_usd_cents")]
        public long? TotalUsdCents { get; set; }
        [JsonProperty("revenue_cents", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("revenue_cents")]
        public long? RevenueCents { get; set; }
        [JsonProperty("revenue_usd_cents")]
        [STJS.JsonPropertyName("revenue_usd_cents")]
        public long? RevenueUsdCents { get; set; }
        [JsonProperty("fee_cents", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("fee_cents")]
        public long? FeeCents { get; set; }
        [JsonProperty("fee_rate")]
        [STJS.JsonPropertyName("fee_rate")]
        public long? FeeRate { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
