// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a list tickets response value200 application json property data item.</summary>
    [SellAppModelSchema(true)]
    public class ListTicketsResponseValue200ApplicationJsonPropertyDataItem
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public long Id { get; set; }
        [JsonProperty("title", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("title")]
        public string Title { get; set; } = default!;
        [JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("status")]
        public string Status { get; set; } = default!;
        [JsonProperty("customer", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("customer")]
        public ListTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomer Customer { get; set; } = default!;
        [JsonProperty("reference", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("reference")]
        public List<string> Reference { get; set; } = default!;
        [JsonProperty("created_at", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; set; }
        [JsonProperty("updated_at", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }
        [JsonProperty("store_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("store_id")]
        public long StoreId { get; set; }
        [JsonProperty("read_by", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("read_by")]
        public long ReadBy { get; set; }
        [JsonProperty("archived", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("archived")]
        public long Archived { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
