// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a list integration events response value200 application json property data item.</summary>
    [SellAppModelSchema(true)]
    public class ListIntegrationEventsResponseValue200ApplicationJsonPropertyDataItem
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        [SellAppSchemaConstraints(Pattern = "^evt_")]
        public string Id { get; set; } = default!;
        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("type")]
        public string Type { get; set; } = default!;
        [JsonProperty("version", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("version")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long Version { get; set; }
        [JsonProperty("store_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("store_id")]
        public string StoreId { get; set; } = default!;
        [JsonProperty("occurred_at", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("occurred_at")]
        public DateTimeOffset OccurredAt { get; set; }
        [JsonProperty("subject", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("subject")]
        public ListIntegrationEventsResponseValue200ApplicationJsonPropertyDataItemPropertySubject Subject { get; set; } = default!;
        [JsonProperty("data", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("data")]
        public ListIntegrationEventsResponseValue200ApplicationJsonPropertyDataItemPropertyData Data { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
