// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a list stores response value200 application json property data item.</summary>
    [SellAppModelSchema(true)]
    public class ListStoresResponseValue200ApplicationJsonPropertyDataItem
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        [JsonProperty("slug", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("slug")]
        public string Slug { get; set; } = default!;
        [JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
