// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a list payment methods response value200 application json property data item.</summary>
    [SellAppModelSchema(true)]
    public class ListPaymentMethodsResponseValue200ApplicationJsonPropertyDataItem
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        [JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("name")]
        public string Name { get; set; } = default!;
        [JsonProperty("description", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("description")]
        public string Description { get; set; } = default!;
        [JsonProperty("category", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("category")]
        public ListPaymentMethodsResponseValue200ApplicationJsonPropertyDataItemCategory Category { get; set; }
        [JsonProperty("connection_type", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("connection_type")]
        public ListPaymentMethodsResponseValue200ApplicationJsonPropertyDataItemConnectionType ConnectionType { get; set; }
        [JsonProperty("status", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("status")]
        public ListPaymentMethodsResponseValue200ApplicationJsonPropertyDataItemStatus Status { get; set; }
        [JsonProperty("enabled", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("enabled")]
        public bool Enabled { get; set; }
        [JsonProperty("health_status", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("health_status")]
        public ListPaymentMethodsResponseValue200ApplicationJsonPropertyDataItemHealthStatus HealthStatus { get; set; }
        [JsonProperty("configuration_supported", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("configuration_supported")]
        public bool ConfigurationSupported { get; set; }
        [JsonProperty("required_input", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("required_input")]
        public List<ListPaymentMethodsResponseValue200ApplicationJsonPropertyDataItemPropertyRequiredInputItem> RequiredInput { get; set; } = default!;

        /// <summary>Short-lived or provider-hosted setup handoff when the method supports OAuth-style connection.</summary>
        [JsonProperty("connect_url", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("connect_url")]
        public string? ConnectUrl { get; set; }
        [JsonProperty("configuration_url", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("configuration_url")]
        public string? ConfigurationUrl { get; set; }
        [JsonProperty("status_url", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("status_url")]
        public string StatusUrl { get; set; } = default!;
        [JsonProperty("actionable_error", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("actionable_error")]
        public string? ActionableError { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
