// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a list payment methods response value200 application json property data item property required input item.</summary>
    [SellAppModelSchema(true)]
    public class ListPaymentMethodsResponseValue200ApplicationJsonPropertyDataItemPropertyRequiredInputItem
    {
        [JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("name")]
        public string Name { get; set; } = default!;
        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("type")]
        public ListPaymentMethodsResponseValue200ApplicationJsonPropertyDataItemPropertyRequiredInputItemType Type { get; set; }
        [JsonProperty("required", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("required")]
        public bool Required { get; set; }

        /// <summary>When true, the corresponding setup value is write-only and is never returned by SellApp.</summary>
        [JsonProperty("secret", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("secret")]
        public bool Secret { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
