// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Present only when default_variant is null. Inspect the state before attempting a purchase.</summary>
    [SellAppModelSchema(true)]
    public class ListCreditsProductsResponseValue200ApplicationJsonAnyOfValue2PropertyDataItemPropertyVariantInvariant
    {
        [JsonProperty("state", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("state")]
        public ListCreditsProductsResponseValue200ApplicationJsonAnyOfValue2PropertyDataItemPropertyVariantInvariantState State { get; set; }
        [JsonProperty("variant_count", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("variant_count")]
        [SellAppSchemaConstraints(Minimum = 0d)]
        public long VariantCount { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
