// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a list invoices response value200 application json property data item property status property status.</summary>
    [SellAppModelSchema(true)]
    public class ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyStatusPropertyStatus
    {
        [JsonProperty("setAt", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("setAt")]
        public DateTimeOffset SetAt { get; set; }
        [JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("status")]
        public string Status { get; set; } = default!;
        [JsonProperty("updatedAt", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("updatedAt")]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
