// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a replace affiliate program configuration request application json property settings property commission.</summary>
    [SellAppModelSchema(true)]
    public class ReplaceAffiliateProgramConfigurationRequestApplicationJsonPropertySettingsPropertyCommission
    {
        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("type")]
        public ReplaceAffiliateProgramConfigurationRequestApplicationJsonPropertySettingsPropertyCommissionType Type { get; set; }

        /// <summary>Decimal commission value. Percentage commissions must be from 0.01 through 100; fixed commissions are USD major units.</summary>
        [JsonProperty("amount", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("amount")]
        public string Amount { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
