// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a replace analytics settings response value200 application json property data.</summary>
    [SellAppModelSchema(true)]
    public class ReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyData
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public long Id { get; set; }
        [JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("name")]
        public string Name { get; set; } = default!;
        [JsonProperty("slug", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("slug")]
        public string Slug { get; set; } = default!;
        [JsonProperty("visibility", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("visibility")]
        public CourseVisibility Visibility { get; set; }
        [JsonProperty("timezone", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("timezone")]
        public string Timezone { get; set; } = default!;
        [JsonProperty("currency", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("currency")]
        [SellAppSchemaConstraints(MinLength = 3, MaxLength = 3)]
        public string Currency { get; set; } = default!;
        [JsonProperty("dark_mode")]
        [STJS.JsonPropertyName("dark_mode")]
        public DarkMode? DarkMode { get; set; }
        [JsonProperty("status", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("status")]
        public ReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyDataPropertyStatus Status { get; set; } = default!;
        [JsonProperty("analytics", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("analytics")]
        public ReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyDataPropertyAnalytics Analytics { get; set; } = default!;
        [JsonProperty("marketing", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("marketing")]
        public ReplaceAnalyticsSettingsResponseValue200ApplicationJsonPropertyDataPropertyMarketing Marketing { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
