// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a rotate webhook signing secret response value200 application json property data.</summary>
    [SellAppModelSchema(true)]
    public class RotateWebhookSigningSecretResponseValue200ApplicationJsonPropertyData
    {
        [JsonProperty("signing_secret_configured", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("signing_secret_configured")]
        public bool SigningSecretConfigured { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
