// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a sdk create export response value201 application json.</summary>
    [SellAppModelSchema(false)]
    public class SdkCreateExportResponseValue201ApplicationJson
    {
        [JsonProperty("data", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("data")]
        public CreateExportResponseValue201ApplicationJsonPropertyData Data { get; set; } = default!;
        [JsonProperty("meta", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("meta")]
        public CreateExportResponseValue201ApplicationJsonPropertyMeta Meta { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
