// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a sdk exchange o auth token response value200 application json.</summary>
    [SellAppModelSchema(true)]
    public class SdkExchangeOAuthTokenResponseValue200ApplicationJson
    {
        [JsonProperty("token_type", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("token_type")]
        public string TokenType { get; internal set; } = "Bearer";
        [JsonProperty("expires_in", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("expires_in")]
        public int ExpiresIn { get; internal set; } = 3600;
        [JsonProperty("access_token", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("access_token")]
        public string AccessToken { get; set; } = default!;
        [JsonProperty("refresh_token", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("refresh_token")]
        public string RefreshToken { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
