// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a sdk replace section products response value200 application json.</summary>
    [SellAppModelSchema(true)]
    public class SdkReplaceSectionProductsResponseValue200ApplicationJson
    {
        [JsonProperty("data", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("data")]
        public ReplaceSectionProductsResponseValue200ApplicationJsonPropertyData Data { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
