// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a sdk search invoices response value200 application json.</summary>
    [SellAppModelSchema(true)]
    public class SdkSearchInvoicesResponseValue200ApplicationJson
    {
        [JsonProperty("data", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("data")]
        public List<SearchInvoicesResponseValue200ApplicationJsonPropertyDataItem> Data { get; set; } = default!;
        [JsonProperty("links", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("links")]
        public SearchInvoicesResponseValue200ApplicationJsonPropertyLinks Links { get; set; } = default!;
        [JsonProperty("meta", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("meta")]
        public SearchInvoicesResponseValue200ApplicationJsonPropertyMeta Meta { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
