// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an update group response value200 application json property data property image value property metadata.</summary>
    [SellAppModelSchema(true)]
    public class UpdateGroupResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata
    {
        [JsonProperty("size")]
        [STJS.JsonPropertyName("size")]
        public long? Size { get; set; }
        [JsonProperty("filename")]
        [STJS.JsonPropertyName("filename")]
        public string? Filename { get; set; }
        [JsonProperty("extension")]
        [STJS.JsonPropertyName("extension")]
        public string? Extension { get; set; }
        [JsonProperty("mime_type")]
        [STJS.JsonPropertyName("mime_type")]
        public string? MimeType { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
