// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an update notification channel request application json property channel.</summary>
    [SellAppModelSchema(true)]
    public class UpdateNotificationChannelRequestApplicationJsonPropertyChannel
    {
        [JsonProperty("type")]
        [STJS.JsonPropertyName("type")]
        public UpdateNotificationChannelRequestApplicationJsonPropertyChannelType? Type { get; set; }
        [JsonProperty("email")]
        [STJS.JsonPropertyName("email")]
        public string? Email { get; set; }
        [JsonProperty("channel")]
        [STJS.JsonPropertyName("channel")]
        public string? Channel { get; set; }
        [JsonProperty("webhook")]
        [STJS.JsonPropertyName("webhook")]
        public string? Webhook { get; set; }
        [JsonProperty("allowed_notifications")]
        [STJS.JsonPropertyName("allowed_notifications")]
        public List<string>? AllowedNotifications { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
