// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents an update group response value200 application json property data.</summary>
    [SellAppModelSchema(true)]
    public class UpdateGroupResponseValue200ApplicationJsonPropertyData
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public long Id { get; set; }
        [JsonProperty("title", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("title")]
        public string Title { get; set; } = default!;
        [JsonProperty("order", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("order")]
        public long Order { get; set; }
        [JsonProperty("image", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("image")]
        public UpdateGroupResponseValue200ApplicationJsonPropertyDataPropertyImage? Image { get; set; }
        [JsonProperty("unlisted", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("unlisted")]
        public bool Unlisted { get; set; }
        [JsonProperty("created_at", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; set; }
        [JsonProperty("updated_at", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }
        [JsonProperty("store_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("store_id")]
        public long StoreId { get; set; }
        [JsonProperty("section_id", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("section_id")]
        public long? SectionId { get; set; }
        [JsonProperty("section_order", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("section_order")]
        public long? SectionOrder { get; set; }
        [JsonProperty("products_linked", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("products_linked")]
        public long ProductsLinked { get; set; }
        [JsonProperty("products", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("products")]
        public List<UpdateGroupResponseValue200ApplicationJsonPropertyDataPropertyProductsItem> Products { get; set; } = default!;

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
