// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Fee or discount for this custom payment method only. Positive values reduce the ordinary order or charge total; negative values add a fee. Percentage is applied first, then the fixed amount once per order or charge in the checkout currency (major units, so 1.50 means $1.50 for USD). Values allow up to two decimal places. Omit modifier to preserve it on updates; send null or an empty object to clear it. A supplied object replaces both values. New methods default to no adjustment. Custom wallet top-ups do not apply these modifiers.</summary>
    [SellAppModelSchema(false)]
    public class UpdateCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyModifier
    {

        /// <summary>Percentage from -100 to 100. For example, 5 gives 5% off and -5 adds a 5% fee. Responses use decimal strings.</summary>
        [JsonProperty("percentage")]
        [STJS.JsonPropertyName("percentage")]
        public OneOf.OneOf<string, double>? Percentage { get; set; }

        /// <summary>Fixed adjustment from -100000 to 100000 in major units of the checkout currency. Responses use decimal strings.</summary>
        [JsonProperty("fixed")]
        [STJS.JsonPropertyName("fixed")]
        public OneOf.OneOf<string, double>? Fixed { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
