// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a V2 replace feedback response value200 application json property data.</summary>
    [SellAppModelSchema(true)]
    public class V2ReplaceFeedbackResponseValue200ApplicationJsonPropertyData
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("id")]
        public long Id { get; set; }
        [JsonProperty("feedback", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("feedback")]
        public string Feedback { get; set; } = default!;
        [JsonProperty("rating", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("rating")]
        public long? Rating { get; set; }
        [JsonProperty("deleted_at", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("deleted_at")]
        public DateTimeOffset? DeletedAt { get; set; }
        [JsonProperty("created_at", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("created_at")]
        public DateTimeOffset? CreatedAt { get; set; }
        [JsonProperty("updated_at", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("updated_at")]
        public DateTimeOffset? UpdatedAt { get; set; }
        [JsonProperty("store_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("store_id")]
        public long StoreId { get; set; }
        [JsonProperty("metadata", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("metadata")]
        public V2ReplaceFeedbackResponseValue200ApplicationJsonPropertyDataPropertyMetadata Metadata { get; set; } = default!;
        [JsonProperty("message", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("message")]
        public string? Message { get; set; }
        [JsonProperty("reply", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("reply")]
        public string? Reply { get; set; }
        [JsonProperty("is_automatic", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("is_automatic")]
        public bool IsAutomatic { get; set; }

        /// <summary>Product associated with the feedback, when available.</summary>
        [JsonProperty("product_id", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("product_id")]
        public long? ProductId { get; set; }

        /// <summary>Purchase associated with the feedback, when available.</summary>
        [JsonProperty("order_id", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("order_id")]
        public long? OrderId { get; set; }
        [JsonProperty("sentiment", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("sentiment")]
        public V2ReplaceFeedbackResponseValue200ApplicationJsonPropertyDataSentiment Sentiment { get; set; }
        [JsonProperty("variant_id", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("variant_id")]
        public long? VariantId { get; set; }
        [JsonProperty("product_title", Required = Newtonsoft.Json.Required.AllowNull)]
        [STJS.JsonPropertyName("product_title")]
        public string? ProductTitle { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
