// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Represents a V2 search feedback request application json property sort item.</summary>
    [SellAppModelSchema(true)]
    public class V2SearchFeedbackRequestApplicationJsonPropertySortItem
    {
        [JsonProperty("field", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("field")]
        public string Field { get; set; } = default!;
        [JsonProperty("direction")]
        [STJS.JsonPropertyName("direction")]
        public V2SearchFeedbackRequestApplicationJsonPropertySortItemDirection? Direction { get; set; }

        /// <summary>Unrecognized response fields preserved for forward compatibility.</summary>
        [JsonExtensionData]
        [STJS.JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; } = new Dictionary<string, object>();
    }
}
