// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="CoursesSectionsService.CreateAsync"/>: Create a course section</summary>
    [SellAppModelSchema(false)]
    public class CoursesSectionsCreateOptions : BaseOptions
    {
        [JsonProperty("title", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("title")]
        [SellAppSchemaConstraints(MaxLength = 255)]
        public string Title { get; set; } = default!;

        [JsonProperty("description")]
        [STJS.JsonPropertyName("description")]
        [SellAppSchemaConstraints(MaxLength = 65535)]
        public string? Description { get; set; }

    }

    /// <summary>Request options for <see cref="CoursesSectionsService.ReplaceAsync"/>: Update a course section</summary>
    [SellAppModelSchema(false)]
    public class CoursesSectionsReplaceOptions : BaseOptions
    {
        [JsonProperty("title")]
        [STJS.JsonPropertyName("title")]
        [SellAppSchemaConstraints(MaxLength = 255)]
        public string? Title { get; set; }

        [JsonProperty("description")]
        [STJS.JsonPropertyName("description")]
        [SellAppSchemaConstraints(MaxLength = 65535)]
        public string? Description { get; set; }

        [JsonProperty("expected_updated_at")]
        [STJS.JsonPropertyName("expected_updated_at")]
        public DateTimeOffset? ExpectedUpdatedAt { get; set; }

    }

    /// <summary>Request options for <see cref="CoursesSectionsService.UpdateAsync"/>: Update a course section</summary>
    [SellAppModelSchema(false)]
    public class CoursesSectionsUpdateOptions : BaseOptions
    {
        [JsonProperty("title")]
        [STJS.JsonPropertyName("title")]
        [SellAppSchemaConstraints(MaxLength = 255)]
        public string? Title { get; set; }

        [JsonProperty("description")]
        [STJS.JsonPropertyName("description")]
        [SellAppSchemaConstraints(MaxLength = 65535)]
        public string? Description { get; set; }

        [JsonProperty("expected_updated_at")]
        [STJS.JsonPropertyName("expected_updated_at")]
        public DateTimeOffset? ExpectedUpdatedAt { get; set; }

    }

    /// <summary>Request options for <see cref="CoursesSectionsService.ReorderAsync"/>: Reorder course sections</summary>
    [SellAppModelSchema(false)]
    public class CoursesSectionsReorderOptions : BaseOptions
    {
        [JsonProperty("resources", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("resources")]
        [SellAppSchemaConstraints(UniqueItems = true)]
        public List<long> Resources { get; set; } = default!;

    }
}
