// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the courses API operations on <see cref="SellAppClient"/>.</summary>
    public class CoursesService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CoursesService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="SellAppConfiguration.SellAppClient"/>.
        /// </summary>
        public CoursesService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="CoursesService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public CoursesService(SellAppClient client) : base(client) { }

        /// <summary>List courses</summary>
        /// <remarks>
        /// List course products and their complete ordered curriculum for the authenticated store. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="SdkListCoursesResponseValue200ApplicationJson"/> results.</returns>
        public virtual async Task<SellAppList<SdkListCoursesResponseValue200ApplicationJson>> ListAsync(CoursesListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "listCourses", false);
            return await this.GetAsync<SellAppList<SdkListCoursesResponseValue200ApplicationJson>>("/v2/courses", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SellAppList<SdkListCoursesResponseValue200ApplicationJson>>> ListWithResponseAsync(CoursesListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.ListAsync(options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="ListAsync"/>.</summary>
        public virtual Task<SellAppList<SdkListCoursesResponseValue200ApplicationJson>> List(CoursesListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ListAsync(options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="ListAsync"/>. Yields individual items across all pages.</summary>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="SdkListCoursesResponseValue200ApplicationJson"/> items.</returns>
        public virtual IAsyncEnumerable<SdkListCoursesResponseValue200ApplicationJson> ListAutoPagingAsync(CoursesListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "listCourses", false);
            return base.ListAutoPagingAsync<SdkListCoursesResponseValue200ApplicationJson>(HttpMethod.Get, "/v2/courses", options, requestOptions, cancellationToken);
        }

        /// <summary>Search courses</summary>
        /// <remarks>
        /// Search courses by title, slug, or description and compose supported filters and sort instructions. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="SdkSearchCoursesResponseValue200ApplicationJson"/> results.</returns>
        public virtual async Task<SellAppList<SdkSearchCoursesResponseValue200ApplicationJson>> SearchAsync(CoursesSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "searchCourses", false);
            return await this.PostAsync<SellAppList<SdkSearchCoursesResponseValue200ApplicationJson>>("/v2/courses/search", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SellAppList<SdkSearchCoursesResponseValue200ApplicationJson>>> SearchWithResponseAsync(CoursesSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.SearchAsync(options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="SearchAsync"/>.</summary>
        public virtual Task<SellAppList<SdkSearchCoursesResponseValue200ApplicationJson>> Search(CoursesSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.SearchAsync(options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="SearchAsync"/>. Yields individual items across all pages.</summary>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="SdkSearchCoursesResponseValue200ApplicationJson"/> items.</returns>
        public virtual IAsyncEnumerable<SdkSearchCoursesResponseValue200ApplicationJson> SearchAutoPagingAsync(CoursesSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "searchCourses", false);
            return base.ListAutoPagingAsync<SdkSearchCoursesResponseValue200ApplicationJson>(HttpMethod.Post, "/v2/courses/search", options, requestOptions, cancellationToken);
        }

        /// <summary>Retrieve a course</summary>
        /// <remarks>
        /// Retrieve one store-scoped course by listing ID or slug with its ordered curriculum. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="course">The course path parameter.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkGetCourseResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkGetCourseResponseValue200ApplicationJson> GetAsync(string course, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "getCourse", false);
            return await this.GetAsync<SdkGetCourseResponseValue200ApplicationJson>($"/v2/courses/{Uri.EscapeDataString(course)}", null, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkGetCourseResponseValue200ApplicationJson>> GetWithResponseAsync(string course, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.GetAsync(course, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="GetAsync"/>.</summary>
        public virtual Task<SdkGetCourseResponseValue200ApplicationJson> Get(string course, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.GetAsync(course, requestOptions, cancellationToken);
        }

        /// <summary>Update a course</summary>
        /// <remarks>
        /// Update course metadata, access configuration, delivery copy, or publication visibility. Public visibility requires a ready promotional video and at least one published lesson. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="course">The course path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkReplaceCourseResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkReplaceCourseResponseValue200ApplicationJson> ReplaceAsync(string course, CoursesReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "replaceCourse", false);
            return await this.PutAsync<SdkReplaceCourseResponseValue200ApplicationJson>($"/v2/courses/{Uri.EscapeDataString(course)}", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkReplaceCourseResponseValue200ApplicationJson>> ReplaceWithResponseAsync(string course, CoursesReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.ReplaceAsync(course, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="ReplaceAsync"/>.</summary>
        public virtual Task<SdkReplaceCourseResponseValue200ApplicationJson> Replace(string course, CoursesReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ReplaceAsync(course, options, requestOptions, cancellationToken);
        }

        /// <summary>Update a course</summary>
        /// <remarks>
        /// Update course metadata, access configuration, delivery copy, or publication visibility. Public visibility requires a ready promotional video and at least one published lesson. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="course">The course path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkUpdateCourseResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkUpdateCourseResponseValue200ApplicationJson> UpdateAsync(string course, CoursesUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "updateCourse", false);
            return await this.PatchAsync<SdkUpdateCourseResponseValue200ApplicationJson>($"/v2/courses/{Uri.EscapeDataString(course)}", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkUpdateCourseResponseValue200ApplicationJson>> UpdateWithResponseAsync(string course, CoursesUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.UpdateAsync(course, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="UpdateAsync"/>.</summary>
        public virtual Task<SdkUpdateCourseResponseValue200ApplicationJson> Update(string course, CoursesUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.UpdateAsync(course, options, requestOptions, cancellationToken);
        }
    }
}
