// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="BlacklistsService.ListAsync"/>: List all blacklist rules</summary>
    [SellAppModelSchema(false)]
    public class BlacklistsListOptions : ListOptions
    {
        /// <summary>Page number to return.</summary>
        [JsonProperty("page")]
        [STJS.JsonPropertyName("page")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? Page { get; set; }

    }

    /// <summary>Request options for <see cref="BlacklistsService.CreateAsync"/>: Create a blacklist rule</summary>
    [SellAppModelSchema(false)]
    public class BlacklistsCreateOptions : BaseOptions
    {
        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("type")]
        public BlacklistType Type { get; set; }

        /// <summary>The value to blacklist.</summary>
        [JsonProperty("data", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("data")]
        public string Data { get; set; } = default!;

        /// <summary>Why this rule is being created.</summary>
        [JsonProperty("description", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("description")]
        public string Description { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="BlacklistsService.UpdateAsync"/>: Update a blacklist rule</summary>
    [SellAppModelSchema(false)]
    public class BlacklistsUpdateOptions : BaseOptions
    {
        [JsonProperty("type")]
        [STJS.JsonPropertyName("type")]
        public BlacklistType? Type { get; set; }

        /// <summary>The updated value to blacklist.</summary>
        [JsonProperty("data")]
        [STJS.JsonPropertyName("data")]
        public string? Data { get; set; }

        /// <summary>The updated reason for this rule.</summary>
        [JsonProperty("description")]
        [STJS.JsonPropertyName("description")]
        public string? Description { get; set; }

    }

    /// <summary>Request options for <see cref="BlacklistsService.V2CreateBlacklistAsync"/>: Create a blacklist rule</summary>
    [SellAppModelSchema(false)]
    public class BlacklistsV2CreateBlacklistOptions : BaseOptions
    {
        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("type")]
        public BlacklistType Type { get; set; }

        /// <summary>The value to blacklist.</summary>
        [JsonProperty("data", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("data")]
        public string Data { get; set; } = default!;

        /// <summary>Why this rule is being created.</summary>
        [JsonProperty("description", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("description")]
        public string Description { get; set; } = default!;

    }

    /// <summary>Request options for <see cref="BlacklistsService.V2ReplaceBlacklistAsync"/>: Replace a blacklist rule</summary>
    [SellAppModelSchema(false)]
    public class BlacklistsV2ReplaceBlacklistOptions : BaseOptions
    {
        [JsonProperty("type")]
        [STJS.JsonPropertyName("type")]
        public BlacklistType? Type { get; set; }

        /// <summary>The updated value to blacklist.</summary>
        [JsonProperty("data")]
        [STJS.JsonPropertyName("data")]
        public string? Data { get; set; }

        /// <summary>The updated reason for this rule.</summary>
        [JsonProperty("description")]
        [STJS.JsonPropertyName("description")]
        public string? Description { get; set; }

    }

    /// <summary>Request options for <see cref="BlacklistsService.V2UpdateBlacklistAsync"/>: Update a blacklist rule</summary>
    [SellAppModelSchema(false)]
    public class BlacklistsV2UpdateBlacklistOptions : BaseOptions
    {
        [JsonProperty("type")]
        [STJS.JsonPropertyName("type")]
        public BlacklistType? Type { get; set; }

        /// <summary>The updated value to blacklist.</summary>
        [JsonProperty("data")]
        [STJS.JsonPropertyName("data")]
        public string? Data { get; set; }

        /// <summary>The updated reason for this rule.</summary>
        [JsonProperty("description")]
        [STJS.JsonPropertyName("description")]
        public string? Description { get; set; }

    }
}
