// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>Service that exposes the product variants API operations on <see cref="SellAppClient"/>.</summary>
    public class ProductVariantsService : Service
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductVariantsService"/> class for mocking. The service uses the singleton
        /// client configured via <see cref="SellAppConfiguration.SellAppClient"/>.
        /// </summary>
        public ProductVariantsService() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductVariantsService"/> class bound to the
        /// supplied <paramref name="client"/>.
        /// </summary>
        /// <param name="client">The HTTP client used to make API requests.</param>
        public ProductVariantsService(SellAppClient client) : base(client) { }

        /// <summary>List all product variants</summary>
        /// <remarks>
        /// List a product's variants, 15 per page by default. Requires a token with the listing ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem"/> results.</returns>
        public virtual async Task<SellAppList<ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem>> ListAsync(string product, ProductVariantsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "listProductVariants", false);
            return await this.GetAsync<SellAppList<ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem>>($"/v2/products/{Uri.EscapeDataString(product)}/variants", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SellAppList<ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem>>> ListWithResponseAsync(string product, ProductVariantsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.ListAsync(product, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="ListAsync"/>.</summary>
        public virtual Task<SellAppList<ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem>> List(string product, ProductVariantsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ListAsync(product, options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="ListAsync"/>. Yields individual items across all pages.</summary>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem"/> items.</returns>
        public virtual IAsyncEnumerable<ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem> ListAutoPagingAsync(string product, ProductVariantsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "listProductVariants", false);
            return base.ListAutoPagingAsync<ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem>(HttpMethod.Get, $"/v2/products/{Uri.EscapeDataString(product)}/variants", options, requestOptions, cancellationToken);
        }

        /// <summary>Create a product variant</summary>
        /// <remarks>
        /// Create a product variant for the authenticated store. Course, credits, and add-on products permit only one variant. Requires a token with the listing ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkCreateProductVariantResponseValue201ApplicationJson"/> result.</returns>
        public virtual async Task<SdkCreateProductVariantResponseValue201ApplicationJson> CreateAsync(string product, ProductVariantsCreateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "createProductVariant", false);
            return await this.PostAsync<SdkCreateProductVariantResponseValue201ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkCreateProductVariantResponseValue201ApplicationJson>> CreateWithResponseAsync(string product, ProductVariantsCreateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.CreateAsync(product, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="CreateAsync"/>.</summary>
        public virtual Task<SdkCreateProductVariantResponseValue201ApplicationJson> Create(string product, ProductVariantsCreateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.CreateAsync(product, options, requestOptions, cancellationToken);
        }

        /// <summary>Retrieve a product variant</summary>
        /// <remarks>
        /// Retrieve a variant using its product ID and variant ID. Requires a token with the listing ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="variant">The variant path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkGetProductVariantResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkGetProductVariantResponseValue200ApplicationJson> GetAsync(string product, string variant, ProductVariantsGetOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "getProductVariant", false);
            return await this.GetAsync<SdkGetProductVariantResponseValue200ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants/{Uri.EscapeDataString(variant)}", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkGetProductVariantResponseValue200ApplicationJson>> GetWithResponseAsync(string product, string variant, ProductVariantsGetOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.GetAsync(product, variant, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="GetAsync"/>.</summary>
        public virtual Task<SdkGetProductVariantResponseValue200ApplicationJson> Get(string product, string variant, ProductVariantsGetOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.GetAsync(product, variant, options, requestOptions, cancellationToken);
        }

        /// <summary>Update a product variant with PUT</summary>
        /// <remarks>
        /// Update a product variant using the PUT compatibility method. Fields remain partial for backward compatibility. Requires a token with the listing ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="variant">The variant path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkReplaceProductVariantWithPutResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkReplaceProductVariantWithPutResponseValue200ApplicationJson> ReplaceAsync(string product, string variant, ProductVariantsReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "replaceProductVariantWithPut", false);
            return await this.PutAsync<SdkReplaceProductVariantWithPutResponseValue200ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants/{Uri.EscapeDataString(variant)}", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkReplaceProductVariantWithPutResponseValue200ApplicationJson>> ReplaceWithResponseAsync(string product, string variant, ProductVariantsReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.ReplaceAsync(product, variant, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="ReplaceAsync"/>.</summary>
        public virtual Task<SdkReplaceProductVariantWithPutResponseValue200ApplicationJson> Replace(string product, string variant, ProductVariantsReplaceOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.ReplaceAsync(product, variant, options, requestOptions, cancellationToken);
        }

        /// <summary>Update a product variant</summary>
        /// <remarks>
        /// Updates a product variant's details. Requires a token with the listing ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="variant">The variant path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkUpdateProductVariantResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkUpdateProductVariantResponseValue200ApplicationJson> UpdateAsync(string product, string variant, ProductVariantsUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "updateProductVariant", false);
            return await this.PatchAsync<SdkUpdateProductVariantResponseValue200ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants/{Uri.EscapeDataString(variant)}", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkUpdateProductVariantResponseValue200ApplicationJson>> UpdateWithResponseAsync(string product, string variant, ProductVariantsUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.UpdateAsync(product, variant, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="UpdateAsync"/>.</summary>
        public virtual Task<SdkUpdateProductVariantResponseValue200ApplicationJson> Update(string product, string variant, ProductVariantsUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.UpdateAsync(product, variant, options, requestOptions, cancellationToken);
        }

        /// <summary>Delete a product variant</summary>
        /// <remarks>
        /// Deletes a product variant. This will permanently delete the product variant and all of its details, including the sensitive deliverables, will no longer be retrievable. Requires a token with the listing ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="variant">The variant path parameter.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        public virtual async Task DeleteAsync(string product, string variant, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "deleteProductVariant", false);
            await base.DeleteAsync($"/v2/products/{Uri.EscapeDataString(product)}/variants/{Uri.EscapeDataString(variant)}", null, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<object?>> DeleteWithResponseAsync(string product, string variant, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            await this.DeleteAsync(product, variant, requestOptions, cancellationToken);
            return capture.Wrap<object?>(null);
        }

        /// <summary>Compatibility wrapper for <see cref="DeleteAsync"/>.</summary>
        public virtual Task Delete(string product, string variant, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.DeleteAsync(product, variant, requestOptions, cancellationToken);
        }

        /// <summary>Search product variants</summary>
        /// <remarks>
        /// Search a product's variants using JSON body filters, search terms, includes, and sort instructions. Requires a token with the listing ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A page of <see cref="SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem"/> results.</returns>
        public virtual async Task<SellAppList<SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem>> SearchAsync(string product, ProductVariantsSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "searchProductVariants", false);
            return await this.PostAsync<SellAppList<SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem>>($"/v2/products/{Uri.EscapeDataString(product)}/variants/search", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SellAppList<SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem>>> SearchWithResponseAsync(string product, ProductVariantsSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.SearchAsync(product, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="SearchAsync"/>.</summary>
        public virtual Task<SellAppList<SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem>> Search(string product, ProductVariantsSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.SearchAsync(product, options, requestOptions, cancellationToken);
        }

        /// <summary>Auto-paging variant of <see cref="SearchAsync"/>. Yields individual items across all pages.</summary>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>An async sequence of <see cref="SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem"/> items.</returns>
        public virtual IAsyncEnumerable<SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem> SearchAutoPagingAsync(string product, ProductVariantsSearchOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "searchProductVariants", false);
            return base.ListAutoPagingAsync<SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem>(HttpMethod.Post, $"/v2/products/{Uri.EscapeDataString(product)}/variants/search", options, requestOptions, cancellationToken);
        }

        /// <summary>Batch create product variants</summary>
        /// <remarks>
        /// Create multiple variants for a product in one request by sending a `resources` array. Requires a token with the listing ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkBatchCreateProductVariantsResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkBatchCreateProductVariantsResponseValue200ApplicationJson> BatchCreateAsync(string product, ProductVariantsBatchCreateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "batchCreateProductVariants", false);
            return await this.PostAsync<SdkBatchCreateProductVariantsResponseValue200ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants/batch", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkBatchCreateProductVariantsResponseValue200ApplicationJson>> BatchCreateWithResponseAsync(string product, ProductVariantsBatchCreateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.BatchCreateAsync(product, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="BatchCreateAsync"/>.</summary>
        public virtual Task<SdkBatchCreateProductVariantsResponseValue200ApplicationJson> BatchCreate(string product, ProductVariantsBatchCreateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.BatchCreateAsync(product, options, requestOptions, cancellationToken);
        }

        /// <summary>Batch update product variants</summary>
        /// <remarks>
        /// Update multiple product variants in one request by sending a `resources` object keyed by variant ID. Requires a token with the listing ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The <see cref="SdkBatchUpdateProductVariantsResponseValue200ApplicationJson"/> result.</returns>
        public virtual async Task<SdkBatchUpdateProductVariantsResponseValue200ApplicationJson> BatchUpdateAsync(string product, ProductVariantsBatchUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "batchUpdateProductVariants", false);
            return await this.PatchAsync<SdkBatchUpdateProductVariantsResponseValue200ApplicationJson>($"/v2/products/{Uri.EscapeDataString(product)}/variants/batch", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<SdkBatchUpdateProductVariantsResponseValue200ApplicationJson>> BatchUpdateWithResponseAsync(string product, ProductVariantsBatchUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            var value = await this.BatchUpdateAsync(product, options, requestOptions, cancellationToken);
            return capture.Wrap(value);
        }

        /// <summary>Compatibility wrapper for <see cref="BatchUpdateAsync"/>.</summary>
        public virtual Task<SdkBatchUpdateProductVariantsResponseValue200ApplicationJson> BatchUpdate(string product, ProductVariantsBatchUpdateOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.BatchUpdateAsync(product, options, requestOptions, cancellationToken);
        }

        /// <summary>Batch delete product variants</summary>
        /// <remarks>
        /// Delete multiple product variants in one request by sending the variant IDs in `resources`. Requires a token with the listing ability. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.
        /// </remarks>
        /// <param name="product">The product path parameter.</param>
        /// <param name="options">Request options.</param>
        /// <param name="requestOptions">Per-request configuration overrides.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        public virtual async Task BatchDeleteAsync(string product, ProductVariantsBatchDeleteOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            requestOptions = RequestOptions.ForOperation(requestOptions, "batchDeleteProductVariants", false);
            await this.DeleteAsync($"/v2/products/{Uri.EscapeDataString(product)}/variants/batch", options, requestOptions, cancellationToken);
        }

        public virtual async Task<ApiResponse<object?>> BatchDeleteWithResponseAsync(string product, ProductVariantsBatchDeleteOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            var capture = new ApiResponseCapture();
            requestOptions = RequestOptions.ForOperation(requestOptions, string.Empty, false);
            requestOptions.Capture = capture;
            await this.BatchDeleteAsync(product, options, requestOptions, cancellationToken);
            return capture.Wrap<object?>(null);
        }

        /// <summary>Compatibility wrapper for <see cref="BatchDeleteAsync"/>.</summary>
        public virtual Task BatchDelete(string product, ProductVariantsBatchDeleteOptions options, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
        {
            return this.BatchDeleteAsync(product, options, requestOptions, cancellationToken);
        }
    }
}
