// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="AffiliatesService.ListAsync"/>: List affiliates</summary>
    [SellAppModelSchema(false)]
    public class AffiliatesListOptions : ListOptions
    {
        /// <summary>Filter by affiliate program status.</summary>
        [JsonProperty("status")]
        [STJS.JsonPropertyName("status")]
        public AffiliatesStatus? Status { get; set; }

        /// <summary>Search affiliate email addresses and profile identifiers.</summary>
        [JsonProperty("search")]
        [STJS.JsonPropertyName("search")]
        [SellAppSchemaConstraints(MaxLength = 255)]
        public string? Search { get; set; }

        /// <summary>Page number to return.</summary>
        [JsonProperty("page")]
        [STJS.JsonPropertyName("page")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? Page { get; set; }

    }

    /// <summary>Request options for <see cref="AffiliatesService.UpdateAsync"/>: Update affiliate status</summary>
    [SellAppModelSchema(false)]
    public class AffiliatesUpdateOptions : BaseOptions
    {
        [JsonProperty("status", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("status")]
        public SdkUpdateAffiliateStatusRequestApplicationJsonStatus Status { get; set; }

    }
}
