// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="VariantSerialsService.ListAsync"/>: List variant serial inventory</summary>
    [SellAppModelSchema(false)]
    public class VariantSerialsListOptions : ListOptions
    {
        /// <summary>Filter inventory by a partial serial value.</summary>
        [JsonProperty("search")]
        [STJS.JsonPropertyName("search")]
        [SellAppSchemaConstraints(MaxLength = 2048)]
        public string? Search { get; set; }

        /// <summary>Page number to return.</summary>
        [JsonProperty("page")]
        [STJS.JsonPropertyName("page")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? Page { get; set; }

    }

    /// <summary>Request options for <see cref="VariantSerialsService.AppendAsync"/>: Append variant serial inventory</summary>
    [SellAppModelSchema(false)]
    public class VariantSerialsAppendOptions : BaseOptions
    {
        /// <summary>Serial values to append or use as the replacement inventory.</summary>
        [JsonProperty("serials", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("serials")]
        [SellAppSchemaConstraints(MinItems = 1, MaxItems = 5000)]
        public List<string> Serials { get; set; } = default!;

        /// <summary>Remove duplicate values from this submitted payload.</summary>
        [JsonProperty("remove_duplicates")]
        [STJS.JsonPropertyName("remove_duplicates")]
        public bool? RemoveDuplicates { get; set; }

    }

    /// <summary>Request options for <see cref="VariantSerialsService.ReplaceAsync"/>: Replace variant serial inventory</summary>
    [SellAppModelSchema(false)]
    public class VariantSerialsReplaceOptions : BaseOptions
    {
        /// <summary>Serial values to append or use as the replacement inventory.</summary>
        [JsonProperty("serials", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("serials")]
        [SellAppSchemaConstraints(MinItems = 1, MaxItems = 5000)]
        public List<string> Serials { get; set; } = default!;

        /// <summary>Remove duplicate values from this submitted payload.</summary>
        [JsonProperty("remove_duplicates")]
        [STJS.JsonPropertyName("remove_duplicates")]
        public bool? RemoveDuplicates { get; set; }

    }

    /// <summary>Request options for <see cref="VariantSerialsService.QueueAsync"/>: Queue a variant serial import</summary>
    [SellAppModelSchema(false)]
    public class VariantSerialsQueueOptions : BaseOptions
    {
        /// <summary>A text file up to 100 MiB.</summary>
        [JsonProperty("file", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("file")]
        [SellAppSchemaConstraints(MinLength = 1)]
        public byte[] File { get; set; } = default!;

        /// <summary>How the uploaded file is split into serials. CUSTOM requires custom_delimiter; sending CUSTOM without it fails validation with a 422.</summary>
        [JsonProperty("parsing_mode", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("parsing_mode")]
        public SdkQueueVariantSerialImportRequestMultipartFormDataParsingMode ParsingMode { get; set; }

        /// <summary>The delimiter to split on. Required when parsing_mode is CUSTOM (omitting it fails validation with a 422); ignored otherwise.</summary>
        [JsonProperty("custom_delimiter")]
        [STJS.JsonPropertyName("custom_delimiter")]
        [SellAppSchemaConstraints(MaxLength = 32)]
        public string? CustomDelimiter { get; set; }

        [JsonProperty("remove_duplicates")]
        [STJS.JsonPropertyName("remove_duplicates")]
        public bool? RemoveDuplicates { get; set; }

        [JsonProperty("mode")]
        [STJS.JsonPropertyName("mode")]
        public SdkQueueVariantSerialImportRequestMultipartFormDataMode? Mode { get; set; }

    }
}
