// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="AffiliateReferralsService.ListAsync"/>: List affiliate referrals</summary>
    [SellAppModelSchema(false)]
    public class AffiliateReferralsListOptions : ListOptions
    {
        /// <summary>Filter by store affiliate ID.</summary>
        [JsonProperty("affiliate_id")]
        [STJS.JsonPropertyName("affiliate_id")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? AffiliateId { get; set; }

        /// <summary>Filter by attributed Order ID.</summary>
        [JsonProperty("order_id")]
        [STJS.JsonPropertyName("order_id")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? OrderId { get; set; }

        /// <summary>Filter by referral status.</summary>
        [JsonProperty("status")]
        [STJS.JsonPropertyName("status")]
        public AffiliateReferralsStatus? Status { get; set; }

        /// <summary>Page number to return.</summary>
        [JsonProperty("page")]
        [STJS.JsonPropertyName("page")]
        [SellAppSchemaConstraints(Minimum = 1d)]
        public long? Page { get; set; }

    }

    /// <summary>Request options for <see cref="AffiliateReferralsService.UpdateAsync"/>: Update referral status</summary>
    [SellAppModelSchema(false)]
    public class AffiliateReferralsUpdateOptions : BaseOptions
    {
        [JsonProperty("status", Required = Newtonsoft.Json.Required.Always, DefaultValueHandling = DefaultValueHandling.Ignore)]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingDefault)]
        [STJS.JsonPropertyName("status")]
        public SdkUpdateReferralStatusRequestApplicationJsonStatus Status { get; set; }

    }
}
