// This file is auto-generated by oagen. Do not edit.

namespace SellApp
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using STJS = System.Text.Json.Serialization;

    /// <summary>Request options for <see cref="SubscriptionsService.CancelAsync"/>: Cancel a subscription</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsCancelOptions : BaseOptions
    {
        [JsonProperty("cancel_at_period_end", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("cancel_at_period_end")]
        public bool CancelAtPeriodEnd { get; set; }

        /// <summary>Request a real refund of the latest payment during immediate cancellation. Cancellation success does not prove refund success; verify provider/order refund records.</summary>
        [JsonProperty("refund_last_payment")]
        [STJS.JsonPropertyName("refund_last_payment")]
        public bool? RefundLastPayment { get; set; }

        /// <summary>Request a prorated refund. Requires refund_last_payment=true. False requests a full latest-payment refund when refund_last_payment is enabled.</summary>
        [JsonProperty("pro_rated_refund")]
        [STJS.JsonPropertyName("pro_rated_refund")]
        public bool? ProRatedRefund { get; set; }

        /// <summary>Optional idempotency key. You may also send this as the Idempotency-Key header.</summary>
        [JsonProperty("idempotency_key")]
        [STJS.JsonPropertyName("idempotency_key")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? IdempotencyKey { get; set; }

    }

    /// <summary>Request options for <see cref="SubscriptionsService.CancelAtPeriodEndAsync"/>: Cancel a subscription at period end</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsCancelAtPeriodEndOptions : BaseOptions
    {
        /// <summary>Optional idempotency key. You may also send this as the Idempotency-Key header.</summary>
        [JsonProperty("idempotency_key")]
        [STJS.JsonPropertyName("idempotency_key")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? IdempotencyKey { get; set; }

        [JsonProperty("reason")]
        [STJS.JsonPropertyName("reason")]
        [SellAppSchemaConstraints(MaxLength = 500)]
        public string? Reason { get; set; }

    }

    /// <summary>Request options for <see cref="SubscriptionsService.CancelImmediatelyAsync"/>: Cancel a subscription immediately</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsCancelImmediatelyOptions : BaseOptions
    {
        /// <summary>Optional idempotency key. You may also send this as the Idempotency-Key header.</summary>
        [JsonProperty("idempotency_key")]
        [STJS.JsonPropertyName("idempotency_key")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? IdempotencyKey { get; set; }

        [JsonProperty("reason")]
        [STJS.JsonPropertyName("reason")]
        [SellAppSchemaConstraints(MaxLength = 500)]
        public string? Reason { get; set; }

        /// <summary>Request a real refund of the latest payment during immediate cancellation. Cancellation success does not prove refund success; verify provider/order refund records.</summary>
        [JsonProperty("refund_last_payment")]
        [STJS.JsonPropertyName("refund_last_payment")]
        public bool? RefundLastPayment { get; set; }

        /// <summary>Request a prorated refund. Requires refund_last_payment=true. False requests a full latest-payment refund when refund_last_payment is enabled.</summary>
        [JsonProperty("pro_rated_refund")]
        [STJS.JsonPropertyName("pro_rated_refund")]
        public bool? ProRatedRefund { get; set; }

    }

    /// <summary>Request options for <see cref="SubscriptionsService.PauseAsync"/>: Pause a subscription</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsPauseOptions : BaseOptions
    {
        /// <summary>Optional idempotency key. You may also send this as the Idempotency-Key header.</summary>
        [JsonProperty("idempotency_key")]
        [STJS.JsonPropertyName("idempotency_key")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? IdempotencyKey { get; set; }

        /// <summary>Use a future date-time at execution time. Automatic resume dates are supported only for Stripe; the shown date is illustrative.</summary>
        [JsonProperty("resume_at")]
        [STJS.JsonPropertyName("resume_at")]
        public DateTimeOffset? ResumeAt { get; set; }

        [JsonProperty("reason")]
        [STJS.JsonPropertyName("reason")]
        [SellAppSchemaConstraints(MaxLength = 500)]
        public string? Reason { get; set; }

    }

    /// <summary>Request options for <see cref="SubscriptionsService.ResumeAsync"/>: Resume a subscription</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsResumeOptions : BaseOptions
    {
        /// <summary>Optional idempotency key. You may also send this as the Idempotency-Key header.</summary>
        [JsonProperty("idempotency_key")]
        [STJS.JsonPropertyName("idempotency_key")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? IdempotencyKey { get; set; }

    }

    /// <summary>Request options for <see cref="SubscriptionsService.UpdatePaymentMethodAsync"/>: Update a subscription payment method</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsUpdatePaymentMethodOptions : BaseOptions
    {
        /// <summary>Optional idempotency key. You may also send this as the Idempotency-Key header.</summary>
        [JsonProperty("idempotency_key")]
        [STJS.JsonPropertyName("idempotency_key")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? IdempotencyKey { get; set; }

    }

    /// <summary>Request options for <see cref="SubscriptionsService.PreviewPlanChangeAsync"/>: Preview a subscription plan change</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsPreviewPlanChangeOptions : BaseOptions
    {
        /// <summary>Optional idempotency key. You may also send this as the Idempotency-Key header.</summary>
        [JsonProperty("idempotency_key")]
        [STJS.JsonPropertyName("idempotency_key")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? IdempotencyKey { get; set; }

        [JsonProperty("target_variant_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("target_variant_id")]
        public long TargetVariantId { get; set; }

        [JsonProperty("effective_timing")]
        [STJS.JsonPropertyName("effective_timing")]
        public SdkPreviewSubscriptionPlanChangeRequestApplicationJsonEffectiveTiming? EffectiveTiming { get; set; }

        [JsonProperty("proration_behavior")]
        [STJS.JsonPropertyName("proration_behavior")]
        public SdkPreviewSubscriptionPlanChangeRequestApplicationJsonProrationBehavior? ProrationBehavior { get; set; }

        [JsonProperty("metadata")]
        [STJS.JsonPropertyName("metadata")]
        public PreviewSubscriptionPlanChangeRequestApplicationJsonPropertyMetadata? Metadata { get; set; }

    }

    /// <summary>Request options for <see cref="SubscriptionsService.ConfirmPlanChangeAsync"/>: Confirm a subscription plan change</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsConfirmPlanChangeOptions : BaseOptions
    {
        /// <summary>Optional idempotency key. You may also send this as the Idempotency-Key header.</summary>
        [JsonProperty("idempotency_key")]
        [STJS.JsonPropertyName("idempotency_key")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? IdempotencyKey { get; set; }

        [JsonProperty("target_variant_id", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("target_variant_id")]
        public long TargetVariantId { get; set; }

        [JsonProperty("preview_token", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("preview_token")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string PreviewToken { get; set; } = default!;

        [JsonProperty("effective_timing")]
        [STJS.JsonPropertyName("effective_timing")]
        public SdkConfirmSubscriptionPlanChangeRequestApplicationJsonEffectiveTiming? EffectiveTiming { get; set; }

        [JsonProperty("proration_behavior")]
        [STJS.JsonPropertyName("proration_behavior")]
        public SdkConfirmSubscriptionPlanChangeRequestApplicationJsonProrationBehavior? ProrationBehavior { get; set; }

        [JsonProperty("metadata")]
        [STJS.JsonPropertyName("metadata")]
        public ConfirmSubscriptionPlanChangeRequestApplicationJsonPropertyMetadata? Metadata { get; set; }

    }

    /// <summary>Request options for <see cref="SubscriptionsService.PreviewRenewalDateAsync"/>: Preview a subscription renewal date change</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsPreviewRenewalDateOptions : BaseOptions
    {
        /// <summary>Optional idempotency key. You may also send this as the Idempotency-Key header.</summary>
        [JsonProperty("idempotency_key")]
        [STJS.JsonPropertyName("idempotency_key")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? IdempotencyKey { get; set; }

        [JsonProperty("renewal_date", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("renewal_date")]
        public DateTimeOffset RenewalDate { get; set; }

        [JsonProperty("reason")]
        [STJS.JsonPropertyName("reason")]
        [SellAppSchemaConstraints(MaxLength = 500)]
        public string? Reason { get; set; }

        [JsonProperty("metadata")]
        [STJS.JsonPropertyName("metadata")]
        public PreviewSubscriptionRenewalDateChangeRequestApplicationJsonPropertyMetadata? Metadata { get; set; }

    }

    /// <summary>Request options for <see cref="SubscriptionsService.ConfirmRenewalDateAsync"/>: Confirm a subscription renewal date change</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsConfirmRenewalDateOptions : BaseOptions
    {
        /// <summary>Optional idempotency key. You may also send this as the Idempotency-Key header.</summary>
        [JsonProperty("idempotency_key")]
        [STJS.JsonPropertyName("idempotency_key")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? IdempotencyKey { get; set; }

        [JsonProperty("renewal_date", Required = Newtonsoft.Json.Required.Always)]
        [STJS.JsonPropertyName("renewal_date")]
        public DateTimeOffset RenewalDate { get; set; }

        [JsonProperty("preview_token")]
        [STJS.JsonPropertyName("preview_token")]
        [SellAppSchemaConstraints(MaxLength = 128)]
        public string? PreviewToken { get; set; }

        [JsonProperty("reason")]
        [STJS.JsonPropertyName("reason")]
        [SellAppSchemaConstraints(MaxLength = 500)]
        public string? Reason { get; set; }

        [JsonProperty("metadata")]
        [STJS.JsonPropertyName("metadata")]
        public ConfirmSubscriptionRenewalDateChangeRequestApplicationJsonPropertyMetadata? Metadata { get; set; }

    }

    /// <summary>Request options for <see cref="SubscriptionsService.SearchAsync"/>: Search subscriptions</summary>
    [SellAppModelSchema(false)]
    public class SubscriptionsSearchOptions : ListOptions
    {
        [JsonProperty("search")]
        [STJS.JsonPropertyName("search")]
        public string? Search { get; set; }

        [JsonProperty("status")]
        [STJS.JsonPropertyName("status")]
        public string? Status { get; set; }

    }
}
