// This file is auto-generated by oagen. Do not edit.

namespace SellAppTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using SellApp;
    using Xunit;

    public class CashbackRulesServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly CashbackRulesService service;

        public CashbackRulesServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new SellAppClient(new SellAppOptions
            {
                ApiKey = "sk_test",
                Store = "store_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new CashbackRulesService(client);
        }

        [Fact]
        public async Task TestListAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_list_cashback_rules_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/v2/cashback-rules", HttpStatusCode.OK, fixture);
            var result = await this.service.ListAsync();
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/v2/cashback-rules");
        }

        [Fact]
        public async Task TestCreateAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_create_cashback_rule_response_value_201_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/cashback-rules", HttpStatusCode.OK, fixture);
            var result = await this.service.CreateAsync(Newtonsoft.Json.JsonConvert.DeserializeObject<CashbackRulesCreateOptions>("{\"percent_basis\":1,\"maximum_cashback_cents\":1,\"is_active\":true,\"product_ids\":[1]}")!);
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/cashback-rules");
        }

        [Fact]
        public async Task TestReplaceAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_replace_cashback_rule_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Put, "/v2/cashback-rules/test_cashbackRule", HttpStatusCode.OK, fixture);
            var result = await this.service.ReplaceAsync("test_cashbackRule", Newtonsoft.Json.JsonConvert.DeserializeObject<CashbackRulesReplaceOptions>("{\"percent_basis\":1,\"maximum_cashback_cents\":1,\"is_active\":true,\"product_ids\":[1]}")!);
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Put, "/v2/cashback-rules/test_cashbackRule");
        }

        [Fact]
        public async Task TestUpdateAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_update_cashback_rule_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/v2/cashback-rules/test_cashbackRule", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdateAsync("test_cashbackRule", new CashbackRulesUpdateOptions());
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/v2/cashback-rules/test_cashbackRule");
        }

        [Fact]
        public async Task TestArchiveAsync()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/v2/cashback-rules/test_cashbackRule", HttpStatusCode.NoContent, "");
            await this.service.ArchiveAsync("test_cashbackRule");
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/v2/cashback-rules/test_cashbackRule");
        }

        [Fact]
        public async Task TestRestoreAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_restore_cashback_rule_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/cashback-rules/test_cashbackRule/restore", HttpStatusCode.OK, fixture);
            var result = await this.service.RestoreAsync("test_cashbackRule");
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/cashback-rules/test_cashbackRule/restore");
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationException>(() => this.service.ListAsync());
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundException>(() => this.service.ListAsync());
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityException>(() => this.service.ListAsync());
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededException>(() => this.service.ListAsync());
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerException>(() => this.service.ListAsync());
        }
    }
}
