// This file is auto-generated by oagen. Do not edit.

namespace SellAppTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using SellApp;
    using Xunit;

    public class CoursesSectionsServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly CoursesSectionsService service;

        public CoursesSectionsServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new SellAppClient(new SellAppOptions
            {
                ApiKey = "sk_test",
                Store = "store_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new CoursesSectionsService(client);
        }

        [Fact]
        public async Task TestCreateAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_create_course_section_response_value_201_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/courses/test_course/sections", HttpStatusCode.OK, fixture);
            var options = Newtonsoft.Json.JsonConvert.DeserializeObject<CoursesSectionsCreateOptions>("{\"title\":\"test_title\"}")!;
            options.Title = "test_title";
            var result = await this.service.CreateAsync("test_course", options);
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/courses/test_course/sections");
            await this.httpMock.AssertRequestBodyContainsAsync("title", "test_title");
        }

        [Fact]
        public async Task TestReplaceAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_replace_course_section_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Put, "/v2/courses/test_course/sections/test_section", HttpStatusCode.OK, fixture);
            var result = await this.service.ReplaceAsync("test_course", "test_section", new CoursesSectionsReplaceOptions());
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Put, "/v2/courses/test_course/sections/test_section");
        }

        [Fact]
        public async Task TestUpdateAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_update_course_section_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/v2/courses/test_course/sections/test_section", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdateAsync("test_course", "test_section", new CoursesSectionsUpdateOptions());
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/v2/courses/test_course/sections/test_section");
        }

        [Fact]
        public async Task TestDeleteAsync()
        {
            this.httpMock.MockResponse(HttpMethod.Delete, "/v2/courses/test_course/sections/test_section", HttpStatusCode.NoContent, "");
            await this.service.DeleteAsync("test_course", "test_section");
            this.httpMock.AssertRequestWasMade(HttpMethod.Delete, "/v2/courses/test_course/sections/test_section");
        }

        [Fact]
        public async Task TestReorderAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_reorder_course_sections_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/v2/courses/test_course/sections/reorder", HttpStatusCode.OK, fixture);
            var result = await this.service.ReorderAsync("test_course", Newtonsoft.Json.JsonConvert.DeserializeObject<CoursesSectionsReorderOptions>("{\"resources\":[1]}")!);
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/v2/courses/test_course/sections/reorder");
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationException>(() => this.service.CreateAsync("test_course", Newtonsoft.Json.JsonConvert.DeserializeObject<CoursesSectionsCreateOptions>("{\"title\":\"test_title\"}")!));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundException>(() => this.service.CreateAsync("test_course", Newtonsoft.Json.JsonConvert.DeserializeObject<CoursesSectionsCreateOptions>("{\"title\":\"test_title\"}")!));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityException>(() => this.service.CreateAsync("test_course", Newtonsoft.Json.JsonConvert.DeserializeObject<CoursesSectionsCreateOptions>("{\"title\":\"test_title\"}")!));
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededException>(() => this.service.CreateAsync("test_course", Newtonsoft.Json.JsonConvert.DeserializeObject<CoursesSectionsCreateOptions>("{\"title\":\"test_title\"}")!));
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerException>(() => this.service.CreateAsync("test_course", Newtonsoft.Json.JsonConvert.DeserializeObject<CoursesSectionsCreateOptions>("{\"title\":\"test_title\"}")!));
        }
    }
}
