// This file is auto-generated by oagen. Do not edit.

namespace SellAppTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using SellApp;
    using Xunit;

    public class CoursesServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly CoursesService service;

        public CoursesServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new SellAppClient(new SellAppOptions
            {
                ApiKey = "sk_test",
                Store = "store_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new CoursesService(client);
        }

        [Fact]
        public async Task TestListAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_sdk_list_courses_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/v2/courses", HttpStatusCode.OK, fixture);
            var result = await this.service.ListAsync(new CoursesListOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/v2/courses");
        }

        [Fact]
        public async Task TestListAsyncEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/v2/courses", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListAsync(new CoursesListOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestSearchAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_sdk_search_courses_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/courses/search", HttpStatusCode.OK, fixture);
            var result = await this.service.SearchAsync(new CoursesSearchOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/courses/search");
        }

        [Fact]
        public async Task TestSearchAsyncEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/courses/search", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.SearchAsync(new CoursesSearchOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestGetAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_get_course_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/v2/courses/test_course", HttpStatusCode.OK, fixture);
            var result = await this.service.GetAsync("test_course");
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/v2/courses/test_course");
        }

        [Fact]
        public async Task TestReplaceAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_replace_course_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Put, "/v2/courses/test_course", HttpStatusCode.OK, fixture);
            var result = await this.service.ReplaceAsync("test_course", new CoursesReplaceOptions());
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Put, "/v2/courses/test_course");
        }

        [Fact]
        public async Task TestUpdateAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_update_course_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/v2/courses/test_course", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdateAsync("test_course", new CoursesUpdateOptions());
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/v2/courses/test_course");
        }

        [Fact]
        public async Task TestListAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_list_courses_response_value_200_application_json.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/v2/courses", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<SdkListCoursesResponseValue200ApplicationJson>();
            await foreach (var item in this.service.ListAutoPagingAsync(new CoursesListOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/v2/courses", HttpStatusCode.OK, new[] { empty });

            var items = new List<SdkListCoursesResponseValue200ApplicationJson>();
            await foreach (var item in this.service.ListAutoPagingAsync(new CoursesListOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestSearchAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_search_courses_response_value_200_application_json.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Post, "/v2/courses/search", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<SdkSearchCoursesResponseValue200ApplicationJson>();
            await foreach (var item in this.service.SearchAutoPagingAsync(new CoursesSearchOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestSearchAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Post, "/v2/courses/search", HttpStatusCode.OK, new[] { empty });

            var items = new List<SdkSearchCoursesResponseValue200ApplicationJson>();
            await foreach (var item in this.service.SearchAutoPagingAsync(new CoursesSearchOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationException>(() => this.service.ListAsync(new CoursesListOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundException>(() => this.service.ListAsync(new CoursesListOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityException>(() => this.service.ListAsync(new CoursesListOptions()));
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededException>(() => this.service.ListAsync(new CoursesListOptions()));
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerException>(() => this.service.ListAsync(new CoursesListOptions()));
        }
    }
}
