// This file is auto-generated by oagen. Do not edit.

namespace SellAppTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using SellApp;
    using Xunit;

    public class InvoicesServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly InvoicesService service;

        public InvoicesServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new SellAppClient(new SellAppOptions
            {
                ApiKey = "sk_test",
                Store = "store_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new InvoicesService(client);
        }

        [Fact]
        public async Task TestListAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_list_invoices_response_value_200_application_json_property_data_item.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/v2/invoices", HttpStatusCode.OK, fixture);
            var result = await this.service.ListAsync(new InvoicesListOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/v2/invoices");
        }

        [Fact]
        public async Task TestListAsyncEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/v2/invoices", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListAsync(new InvoicesListOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestCreateAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_create_invoice_response_value_201_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/invoices", HttpStatusCode.OK, fixture);
            var options = Newtonsoft.Json.JsonConvert.DeserializeObject<InvoicesCreateOptions>("{\"customer_email\":\"test@example.com\",\"payment_method\":\"AUTHNET\",\"product_variants\":{}}")!;
            options.CustomerEmail = "test@example.com";
            var result = await this.service.CreateAsync(options);
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/invoices");
            await this.httpMock.AssertRequestBodyContainsAsync("customer_email", "test@example.com");
        }

        [Fact]
        public async Task TestSearchAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_search_invoices_response_value_200_application_json_property_data_item.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/invoices/search", HttpStatusCode.OK, fixture);
            var result = await this.service.SearchAsync(new InvoicesSearchOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/invoices/search");
        }

        [Fact]
        public async Task TestSearchAsyncEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/invoices/search", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.SearchAsync(new InvoicesSearchOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestGetAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_get_invoice_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/v2/invoices/test_invoice", HttpStatusCode.OK, fixture);
            var result = await this.service.GetAsync("test_invoice");
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/v2/invoices/test_invoice");
        }

        [Fact]
        public async Task TestGoToCheckoutAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_create_checkout_session_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/invoices/test_invoice/checkout", HttpStatusCode.OK, fixture);
            var result = await this.service.GoToCheckoutAsync("test_invoice");
            Assert.NotNull(result);
            Assert.Equal("test_message", result.Message);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/invoices/test_invoice/checkout");
        }

        [Fact]
        public async Task TestGetDeliverablesAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_get_invoice_deliverables_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/v2/invoices/test_invoice/deliverables", HttpStatusCode.OK, fixture);
            var result = await this.service.GetDeliverablesAsync("test_invoice");
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/v2/invoices/test_invoice/deliverables");
        }

        [Fact]
        public async Task TestMarkCompletedAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_mark_pending_invoice_completed_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/v2/invoices/test_invoice/mark-completed", HttpStatusCode.OK, fixture);
            var result = await this.service.MarkCompletedAsync("test_invoice", new InvoicesMarkCompletedOptions());
            Assert.NotNull(result);
            Assert.Equal(1, result.Id);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/v2/invoices/test_invoice/mark-completed");
        }

        [Fact]
        public async Task TestMarkVoidedAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_mark_pending_invoice_voided_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/v2/invoices/test_invoice/mark-voided", HttpStatusCode.OK, fixture);
            var result = await this.service.MarkVoidedAsync("test_invoice", new InvoicesMarkVoidedOptions());
            Assert.NotNull(result);
            Assert.Equal(1, result.Id);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/v2/invoices/test_invoice/mark-voided");
        }

        [Fact]
        public async Task TestIssueReplacementAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_issue_replacement_for_completed_invoice_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/v2/invoices/test_invoice/issue-replacement", HttpStatusCode.OK, fixture);
            var result = await this.service.IssueReplacementAsync("test_invoice", Newtonsoft.Json.JsonConvert.DeserializeObject<InvoicesIssueReplacementOptions>("{\"product_variants\":{}}")!);
            Assert.NotNull(result);
            Assert.Equal(1, result.Id);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/v2/invoices/test_invoice/issue-replacement");
        }

        [Fact]
        public async Task TestUpdateStatusAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_update_invoice_status_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Patch, "/v2/invoices/test_invoice/status", HttpStatusCode.OK, fixture);
            var result = await this.service.UpdateStatusAsync("test_invoice", Newtonsoft.Json.JsonConvert.DeserializeObject<InvoicesUpdateStatusOptions>("{\"status\":\"COMPLETED\"}")!);
            Assert.NotNull(result);
            Assert.Equal(1, result.Id);
            this.httpMock.AssertRequestWasMade(HttpMethod.Patch, "/v2/invoices/test_invoice/status");
        }

        [Fact]
        public async Task TestCreateRefundAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_create_invoice_refund_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/invoices/test_invoice/refunds", HttpStatusCode.OK, fixture);
            var result = await this.service.CreateRefundAsync("test_invoice", new InvoicesCreateRefundOptions());
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/invoices/test_invoice/refunds");
        }

        [Fact]
        public async Task TestRetryFulfillmentAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_create_fulfillment_retry_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/invoices/test_invoice/fulfillment-retries", HttpStatusCode.OK, fixture);
            var result = await this.service.RetryFulfillmentAsync("test_invoice", new InvoicesRetryFulfillmentOptions());
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/invoices/test_invoice/fulfillment-retries");
        }

        [Fact]
        public async Task TestRetryDynamicDeliveryAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_create_dynamic_delivery_retry_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/invoices/test_invoice/dynamic-delivery-retries", HttpStatusCode.OK, fixture);
            var result = await this.service.RetryDynamicDeliveryAsync("test_invoice", Newtonsoft.Json.JsonConvert.DeserializeObject<InvoicesRetryDynamicDeliveryOptions>("{\"delivered_product_id\":42}")!);
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/invoices/test_invoice/dynamic-delivery-retries");
        }

        [Fact]
        public async Task TestNotifyFulfillmentAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_create_fulfillment_notifications_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Post, "/v2/invoices/test_invoice/fulfillment-notifications", HttpStatusCode.OK, fixture);
            var result = await this.service.NotifyFulfillmentAsync("test_invoice", new InvoicesNotifyFulfillmentOptions());
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Post, "/v2/invoices/test_invoice/fulfillment-notifications");
        }

        [Fact]
        public async Task TestListAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_invoices_response_value_200_application_json_property_data_item.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/v2/invoices", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<ListInvoicesResponseValue200ApplicationJsonPropertyDataItem>();
            await foreach (var item in this.service.ListAutoPagingAsync(new InvoicesListOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/v2/invoices", HttpStatusCode.OK, new[] { empty });

            var items = new List<ListInvoicesResponseValue200ApplicationJsonPropertyDataItem>();
            await foreach (var item in this.service.ListAutoPagingAsync(new InvoicesListOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestSearchAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/search_invoices_response_value_200_application_json_property_data_item.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Post, "/v2/invoices/search", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<SearchInvoicesResponseValue200ApplicationJsonPropertyDataItem>();
            await foreach (var item in this.service.SearchAutoPagingAsync(new InvoicesSearchOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestSearchAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Post, "/v2/invoices/search", HttpStatusCode.OK, new[] { empty });

            var items = new List<SearchInvoicesResponseValue200ApplicationJsonPropertyDataItem>();
            await foreach (var item in this.service.SearchAutoPagingAsync(new InvoicesSearchOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationException>(() => this.service.ListAsync(new InvoicesListOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundException>(() => this.service.ListAsync(new InvoicesListOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityException>(() => this.service.ListAsync(new InvoicesListOptions()));
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededException>(() => this.service.ListAsync(new InvoicesListOptions()));
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerException>(() => this.service.ListAsync(new InvoicesListOptions()));
        }
    }
}
