// This file is auto-generated by oagen. Do not edit.

namespace SellAppTests
{
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    using SellApp;
    using Xunit;

    public class ProductsAddonsServiceTest
    {
        private readonly HttpMock httpMock;
        private readonly ProductsAddonsService service;

        public ProductsAddonsServiceTest()
        {
            this.httpMock = new HttpMock();
            var client = new SellAppClient(new SellAppOptions
            {
                ApiKey = "sk_test",
                Store = "store_test",
                HttpClient = this.httpMock.HttpClient,
            });
            this.service = new ProductsAddonsService(client);
        }

        [Fact]
        public async Task TestListAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/list_sdk_list_product_s_add_ons_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Get, "/v2/products/test_product/addons", HttpStatusCode.OK, fixture);
            var result = await this.service.ListAsync("test_product", new ProductsAddonsListOptions());
            Assert.NotNull(result);
            Assert.NotEmpty(result.Data);
            this.httpMock.AssertRequestWasMade(HttpMethod.Get, "/v2/products/test_product/addons");
        }

        [Fact]
        public async Task TestListAsyncEmpty()
        {
            this.httpMock.MockResponse(HttpMethod.Get, "/v2/products/test_product/addons", HttpStatusCode.OK, "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}");
            var result = await this.service.ListAsync("test_product", new ProductsAddonsListOptions());
            Assert.NotNull(result);
            Assert.Empty(result.Data);
        }

        [Fact]
        public async Task TestReplaceAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_replace_product_s_add_ons_response_value_200_application_json.json");
            this.httpMock.MockResponse(HttpMethod.Put, "/v2/products/test_product/addons", HttpStatusCode.OK, fixture);
            var result = await this.service.ReplaceAsync("test_product", Newtonsoft.Json.JsonConvert.DeserializeObject<ProductsAddonsReplaceOptions>("{\"resources\":[1]}")!);
            Assert.NotNull(result);
            this.httpMock.AssertRequestWasMade(HttpMethod.Put, "/v2/products/test_product/addons");
        }

        [Fact]
        public async Task TestListAutoPagingAsync()
        {
            var fixture = System.IO.File.ReadAllText("testdata/sdk_list_product_s_add_ons_response_value_200_application_json.json");
            var page1 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":\"cursor_123\"}}";
            var page2 = "{\"data\":[" + fixture + "],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/v2/products/test_product/addons", HttpStatusCode.OK, new[] { page1, page2 });

            var items = new List<SdkListProductSAddOnsResponseValue200ApplicationJson>();
            await foreach (var item in this.service.ListAutoPagingAsync("test_product", new ProductsAddonsListOptions()))
            {
                items.Add(item);
            }

            Assert.Equal(2, items.Count);
        }

        [Fact]
        public async Task TestListAutoPagingAsyncEmpty()
        {
            var empty = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}";
            this.httpMock.MockSequentialResponses(HttpMethod.Get, "/v2/products/test_product/addons", HttpStatusCode.OK, new[] { empty });

            var items = new List<SdkListProductSAddOnsResponseValue200ApplicationJson>();
            await foreach (var item in this.service.ListAutoPagingAsync("test_product", new ProductsAddonsListOptions()))
            {
                items.Add(item);
            }

            Assert.Empty(items);
        }

        [Fact]
        public async Task TestError401()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.Unauthorized, "{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}");
            await Assert.ThrowsAsync<AuthenticationException>(() => this.service.ListAsync("test_product", new ProductsAddonsListOptions()));
        }

        [Fact]
        public async Task TestError404()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.NotFound, "{\"code\":\"not_found\",\"message\":\"Not Found\"}");
            await Assert.ThrowsAsync<NotFoundException>(() => this.service.ListAsync("test_product", new ProductsAddonsListOptions()));
        }

        [Fact]
        public async Task TestError422()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)422, "{\"code\":\"unprocessable_entity\",\"message\":\"Unprocessable\"}");
            await Assert.ThrowsAsync<UnprocessableEntityException>(() => this.service.ListAsync("test_product", new ProductsAddonsListOptions()));
        }

        [Fact]
        public async Task TestError429()
        {
            this.httpMock.MockResponseForAnyRequest((HttpStatusCode)429, "{\"code\":\"too_many_requests\",\"message\":\"Too Many Requests\"}");
            await Assert.ThrowsAsync<RateLimitExceededException>(() => this.service.ListAsync("test_product", new ProductsAddonsListOptions()));
        }

        [Fact]
        public async Task TestError500()
        {
            this.httpMock.MockResponseForAnyRequest(HttpStatusCode.InternalServerError, "{\"code\":\"server_error\",\"message\":\"Server Error\"}");
            await Assert.ThrowsAsync<ServerException>(() => this.service.ListAsync("test_product", new ProductsAddonsListOptions()));
        }
    }
}
